//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetUsers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AspNetUsers()
        {
            this.TSql_App = new HashSet<TSql_App>();
            this.TSql_Company = new HashSet<TSql_Company>();
            this.TSql_Company1 = new HashSet<TSql_Company>();
            this.TSql_Company2 = new HashSet<TSql_Company>();
            this.TSql_Company3 = new HashSet<TSql_Company>();
            this.TSql_Countrys = new HashSet<TSql_Countrys>();
            this.TSql_Countrys1 = new HashSet<TSql_Countrys>();
            this.TSql_DefaultDesign = new HashSet<TSql_DefaultDesign>();
            this.TSql_DefaultDesign1 = new HashSet<TSql_DefaultDesign>();
            this.TSql_DefaultDesign2 = new HashSet<TSql_DefaultDesign>();
            this.TSql_DefaultDesign3 = new HashSet<TSql_DefaultDesign>();
            this.TSql_DefaultDesign4 = new HashSet<TSql_DefaultDesign>();
            this.TSql_DefaultDesign5 = new HashSet<TSql_DefaultDesign>();
            this.TSql_DesignCamera = new HashSet<TSql_DesignCamera>();
            this.TSql_DesignCamera1 = new HashSet<TSql_DesignCamera>();
            this.TSql_DesignDetails = new HashSet<TSql_DesignDetails>();
            this.TSql_DesignDetails1 = new HashSet<TSql_DesignDetails>();
            this.TSql_Employee = new HashSet<TSql_Employee>();
            this.TSql_Employee1 = new HashSet<TSql_Employee>();
            this.TSql_Employee2 = new HashSet<TSql_Employee>();
            this.TSql_Register = new HashSet<TSql_Register>();
            this.TSql_Register1 = new HashSet<TSql_Register>();
            this.Tsql_RemplaceArticleStok = new HashSet<Tsql_RemplaceArticleStok>();
            this.Tsql_RemplaceArticleStok1 = new HashSet<Tsql_RemplaceArticleStok>();
            this.Tsql_RemplaceArticleStokChildren = new HashSet<Tsql_RemplaceArticleStokChildren>();
            this.Tsql_RemplaceArticleStokChildren1 = new HashSet<Tsql_RemplaceArticleStokChildren>();
            this.TSql_Roles = new HashSet<TSql_Roles>();
            this.TSql_Roles1 = new HashSet<TSql_Roles>();
            this.TSql_System = new HashSet<TSql_System>();
            this.TSql_System1 = new HashSet<TSql_System>();
            this.TSql_TapeInialEndWallIMoreThan300 = new HashSet<TSql_TapeInialEndWallIMoreThan300>();
            this.TSql_TapeInialEndWallIMoreThan3001 = new HashSet<TSql_TapeInialEndWallIMoreThan300>();
            this.TSql_TapeInialEndWallIMoreThan3002 = new HashSet<TSql_TapeInialEndWallIMoreThan300>();
            this.TSql_TapeInialEndWallIsLessThan300 = new HashSet<TSql_TapeInialEndWallIsLessThan300>();
            this.TSql_TapeInialEndWallIsLessThan3001 = new HashSet<TSql_TapeInialEndWallIsLessThan300>();
            this.TSql_TemporalList = new HashSet<TSql_TemporalList>();
            this.TSql_TemporalList1 = new HashSet<TSql_TemporalList>();
            this.TSql_Help = new HashSet<TSql_Help>();
            this.TSql_Help1 = new HashSet<TSql_Help>();
            this.TSql_HelpGrup = new HashSet<TSql_HelpGrup>();
            this.TSql_HelpGrup1 = new HashSet<TSql_HelpGrup>();
            this.TSql_TotalListsDesing = new HashSet<TSql_TotalListsDesing>();
            this.TSql_TotalListsDesing1 = new HashSet<TSql_TotalListsDesing>();
            this.TSql_ConfigDesing = new HashSet<TSql_ConfigDesing>();
            this.TSql_ConfigDesing1 = new HashSet<TSql_ConfigDesing>();
            this.TSql_ConfigDesing2 = new HashSet<TSql_ConfigDesing>();
            this.TSql_Design = new HashSet<TSql_Design>();
            this.TSql_Design1 = new HashSet<TSql_Design>();
            this.TSql_RollGrupDesing = new HashSet<TSql_RollGrupDesing>();
            this.TSql_RollGrupDesing1 = new HashSet<TSql_RollGrupDesing>();
            this.Tsql_Master_Articles = new HashSet<Tsql_Master_Articles>();
            this.Tsql_Master_Articles1 = new HashSet<Tsql_Master_Articles>();
            this.TSql_PluginDeviceAuth = new HashSet<TSql_PluginDeviceAuth>();
            this.TSql_RolesFuntionUser = new HashSet<TSql_RolesFuntionUser>();
            this.TSql_RolesFuntionUser1 = new HashSet<TSql_RolesFuntionUser>();
            this.TSql_RollFunctions = new HashSet<TSql_RollFunctions>();
            this.TSql_RollFunctions1 = new HashSet<TSql_RollFunctions>();
            this.TSql_Client_V2 = new HashSet<TSql_Client_V2>();
            this.TSql_Client_V21 = new HashSet<TSql_Client_V2>();
            this.TSql_DocumentType = new HashSet<TSql_DocumentType>();
            this.TSql_DocumentType1 = new HashSet<TSql_DocumentType>();
            this.TSql_DocumentTypeExtension = new HashSet<TSql_DocumentTypeExtension>();
            this.TSql_DocumentTypeExtension1 = new HashSet<TSql_DocumentTypeExtension>();
            this.TSql_Extension = new HashSet<TSql_Extension>();
            this.TSql_Extension1 = new HashSet<TSql_Extension>();
            this.TSql_Extension2 = new HashSet<TSql_Extension>();
            this.TSql_Extension3 = new HashSet<TSql_Extension>();
            this.TSql_Document = new HashSet<TSql_Document>();
            this.TSql_Document1 = new HashSet<TSql_Document>();
            this.TSql_Offers = new HashSet<TSql_Offers>();
            this.TSql_Offers1 = new HashSet<TSql_Offers>();
            this.TSql_OfferState = new HashSet<TSql_OfferState>();
            this.TSql_OfferState1 = new HashSet<TSql_OfferState>();
            this.TSql_ConfigDesingDefault = new HashSet<TSql_ConfigDesingDefault>();
            this.TSql_ConfigDesingDefault1 = new HashSet<TSql_ConfigDesingDefault>();
            this.TSql_language = new HashSet<TSql_language>();
            this.TSql_language1 = new HashSet<TSql_language>();
            this.TSql_UiTranslation = new HashSet<TSql_UiTranslation>();
            this.TSql_UiTranslation1 = new HashSet<TSql_UiTranslation>();
            this.TSql_Jobside = new HashSet<TSql_Jobside>();
            this.TSql_Jobside1 = new HashSet<TSql_Jobside>();
            this.TSql_Design_V2 = new HashSet<TSql_Design_V2>();
            this.TSql_Design_V21 = new HashSet<TSql_Design_V2>();
            this.TSql_Branch = new HashSet<TSql_Branch>();
            this.TSql_Branch1 = new HashSet<TSql_Branch>();
        }
    
        public string Id { get; set; }
        public string Email { get; set; }
        public bool EmailConfirmed { get; set; }
        public string PasswordHash { get; set; }
        public string SecurityStamp { get; set; }
        public string PhoneNumber { get; set; }
        public bool PhoneNumberConfirmed { get; set; }
        public bool TwoFactorEnabled { get; set; }
        public Nullable<System.DateTime> LockoutEndDateUtc { get; set; }
        public bool LockoutEnabled { get; set; }
        public int AccessFailedCount { get; set; }
        public string UserName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_App> TSql_App { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_Company> TSql_Company { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_Company> TSql_Company1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_Company> TSql_Company2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_Company> TSql_Company3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_Countrys> TSql_Countrys { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_Countrys> TSql_Countrys1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_DefaultDesign> TSql_DefaultDesign { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_DefaultDesign> TSql_DefaultDesign1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_DefaultDesign> TSql_DefaultDesign2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_DefaultDesign> TSql_DefaultDesign3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_DefaultDesign> TSql_DefaultDesign4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_DefaultDesign> TSql_DefaultDesign5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_DesignCamera> TSql_DesignCamera { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_DesignCamera> TSql_DesignCamera1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_DesignDetails> TSql_DesignDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_DesignDetails> TSql_DesignDetails1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_Employee> TSql_Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_Employee> TSql_Employee1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_Employee> TSql_Employee2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_Register> TSql_Register { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_Register> TSql_Register1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tsql_RemplaceArticleStok> Tsql_RemplaceArticleStok { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tsql_RemplaceArticleStok> Tsql_RemplaceArticleStok1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tsql_RemplaceArticleStokChildren> Tsql_RemplaceArticleStokChildren { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tsql_RemplaceArticleStokChildren> Tsql_RemplaceArticleStokChildren1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_Roles> TSql_Roles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_Roles> TSql_Roles1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_System> TSql_System { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_System> TSql_System1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_TapeInialEndWallIMoreThan300> TSql_TapeInialEndWallIMoreThan300 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_TapeInialEndWallIMoreThan300> TSql_TapeInialEndWallIMoreThan3001 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_TapeInialEndWallIMoreThan300> TSql_TapeInialEndWallIMoreThan3002 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_TapeInialEndWallIsLessThan300> TSql_TapeInialEndWallIsLessThan300 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_TapeInialEndWallIsLessThan300> TSql_TapeInialEndWallIsLessThan3001 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_TemporalList> TSql_TemporalList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_TemporalList> TSql_TemporalList1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_Help> TSql_Help { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_Help> TSql_Help1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_HelpGrup> TSql_HelpGrup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_HelpGrup> TSql_HelpGrup1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_TotalListsDesing> TSql_TotalListsDesing { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_TotalListsDesing> TSql_TotalListsDesing1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_ConfigDesing> TSql_ConfigDesing { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_ConfigDesing> TSql_ConfigDesing1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_ConfigDesing> TSql_ConfigDesing2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_Design> TSql_Design { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_Design> TSql_Design1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_RollGrupDesing> TSql_RollGrupDesing { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_RollGrupDesing> TSql_RollGrupDesing1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tsql_Master_Articles> Tsql_Master_Articles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tsql_Master_Articles> Tsql_Master_Articles1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_PluginDeviceAuth> TSql_PluginDeviceAuth { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_RolesFuntionUser> TSql_RolesFuntionUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_RolesFuntionUser> TSql_RolesFuntionUser1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_RollFunctions> TSql_RollFunctions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_RollFunctions> TSql_RollFunctions1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_Client_V2> TSql_Client_V2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_Client_V2> TSql_Client_V21 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_DocumentType> TSql_DocumentType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_DocumentType> TSql_DocumentType1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_DocumentTypeExtension> TSql_DocumentTypeExtension { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_DocumentTypeExtension> TSql_DocumentTypeExtension1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_Extension> TSql_Extension { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_Extension> TSql_Extension1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_Extension> TSql_Extension2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_Extension> TSql_Extension3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_Document> TSql_Document { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_Document> TSql_Document1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_Offers> TSql_Offers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_Offers> TSql_Offers1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_OfferState> TSql_OfferState { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_OfferState> TSql_OfferState1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_ConfigDesingDefault> TSql_ConfigDesingDefault { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_ConfigDesingDefault> TSql_ConfigDesingDefault1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_language> TSql_language { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_language> TSql_language1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_UiTranslation> TSql_UiTranslation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_UiTranslation> TSql_UiTranslation1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_Jobside> TSql_Jobside { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_Jobside> TSql_Jobside1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_Design_V2> TSql_Design_V2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_Design_V2> TSql_Design_V21 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_Branch> TSql_Branch { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_Branch> TSql_Branch1 { get; set; }
    }
}
