//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetUsers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AspNetUsers()
        {
            this.TSql_App = new HashSet<TSql_App>();
            this.TSql_Company = new HashSet<TSql_Company>();
            this.TSql_Company1 = new HashSet<TSql_Company>();
            this.TSql_Company2 = new HashSet<TSql_Company>();
            this.TSql_Company3 = new HashSet<TSql_Company>();
            this.TSql_Countrys = new HashSet<TSql_Countrys>();
            this.TSql_Countrys1 = new HashSet<TSql_Countrys>();
            this.TSql_DefaultDesign = new HashSet<TSql_DefaultDesign>();
            this.TSql_DefaultDesign1 = new HashSet<TSql_DefaultDesign>();
            this.TSql_DefaultDesign2 = new HashSet<TSql_DefaultDesign>();
            this.TSql_DefaultDesign3 = new HashSet<TSql_DefaultDesign>();
            this.TSql_DefaultDesign4 = new HashSet<TSql_DefaultDesign>();
            this.TSql_DefaultDesign5 = new HashSet<TSql_DefaultDesign>();
            this.TSql_DesignCamera = new HashSet<TSql_DesignCamera>();
            this.TSql_DesignCamera1 = new HashSet<TSql_DesignCamera>();
            this.TSql_DesignDetails = new HashSet<TSql_DesignDetails>();
            this.TSql_DesignDetails1 = new HashSet<TSql_DesignDetails>();
            this.TSql_Employee = new HashSet<TSql_Employee>();
            this.TSql_Employee1 = new HashSet<TSql_Employee>();
            this.TSql_Employee2 = new HashSet<TSql_Employee>();
            this.TSql_Register = new HashSet<TSql_Register>();
            this.TSql_Register1 = new HashSet<TSql_Register>();
            this.Tsql_RemplaceArticleStok = new HashSet<Tsql_RemplaceArticleStok>();
            this.Tsql_RemplaceArticleStok1 = new HashSet<Tsql_RemplaceArticleStok>();
            this.Tsql_RemplaceArticleStokChildren = new HashSet<Tsql_RemplaceArticleStokChildren>();
            this.Tsql_RemplaceArticleStokChildren1 = new HashSet<Tsql_RemplaceArticleStokChildren>();
            this.TSql_Roles = new HashSet<TSql_Roles>();
            this.TSql_Roles1 = new HashSet<TSql_Roles>();
            this.TSql_System = new HashSet<TSql_System>();
            this.TSql_System1 = new HashSet<TSql_System>();
            this.TSql_TapeInialEndWallIMoreThan300 = new HashSet<TSql_TapeInialEndWallIMoreThan300>();
            this.TSql_TapeInialEndWallIMoreThan3001 = new HashSet<TSql_TapeInialEndWallIMoreThan300>();
            this.TSql_TapeInialEndWallIMoreThan3002 = new HashSet<TSql_TapeInialEndWallIMoreThan300>();
            this.TSql_TapeInialEndWallIsLessThan300 = new HashSet<TSql_TapeInialEndWallIsLessThan300>();
            this.TSql_TapeInialEndWallIsLessThan3001 = new HashSet<TSql_TapeInialEndWallIsLessThan300>();
            this.TSql_TemporalList = new HashSet<TSql_TemporalList>();
            this.TSql_TemporalList1 = new HashSet<TSql_TemporalList>();
            this.TSql_Help = new HashSet<TSql_Help>();
            this.TSql_Help1 = new HashSet<TSql_Help>();
            this.TSql_HelpGrup = new HashSet<TSql_HelpGrup>();
            this.TSql_HelpGrup1 = new HashSet<TSql_HelpGrup>();
            this.TSql_TotalListsDesing = new HashSet<TSql_TotalListsDesing>();
            this.TSql_TotalListsDesing1 = new HashSet<TSql_TotalListsDesing>();
            this.TSql_ConfigDesingDefault = new HashSet<TSql_ConfigDesingDefault>();
            this.TSql_ConfigDesingDefault1 = new HashSet<TSql_ConfigDesingDefault>();
            this.TSql_ConfigDesing = new HashSet<TSql_ConfigDesing>();
            this.TSql_ConfigDesing1 = new HashSet<TSql_ConfigDesing>();
            this.TSql_ConfigDesing2 = new HashSet<TSql_ConfigDesing>();
            this.TSql_Design = new HashSet<TSql_Design>();
            this.TSql_Design1 = new HashSet<TSql_Design>();
            this.TSql_RollGrupDesing = new HashSet<TSql_RollGrupDesing>();
            this.TSql_RollGrupDesing1 = new HashSet<TSql_RollGrupDesing>();
            this.TSql_RollFunctionsUser = new HashSet<TSql_RollFunctionsUser>();
            this.TSql_RollFunctionsUser1 = new HashSet<TSql_RollFunctionsUser>();
            this.TSql_User_Roles = new HashSet<TSql_User_Roles>();
            this.TSql_User_Roles1 = new HashSet<TSql_User_Roles>();
            this.TSql_User_Roles2 = new HashSet<TSql_User_Roles>();
            this.Tsql_Master_Articles = new HashSet<Tsql_Master_Articles>();
            this.Tsql_Master_Articles1 = new HashSet<Tsql_Master_Articles>();
        }
    
        public string Id { get; set; }
        public string Email { get; set; }
        public bool EmailConfirmed { get; set; }
        public string PasswordHash { get; set; }
        public string SecurityStamp { get; set; }
        public string PhoneNumber { get; set; }
        public bool PhoneNumberConfirmed { get; set; }
        public bool TwoFactorEnabled { get; set; }
        public Nullable<System.DateTime> LockoutEndDateUtc { get; set; }
        public bool LockoutEnabled { get; set; }
        public int AccessFailedCount { get; set; }
        public string UserName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_App> TSql_App { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_Company> TSql_Company { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_Company> TSql_Company1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_Company> TSql_Company2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_Company> TSql_Company3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_Countrys> TSql_Countrys { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_Countrys> TSql_Countrys1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_DefaultDesign> TSql_DefaultDesign { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_DefaultDesign> TSql_DefaultDesign1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_DefaultDesign> TSql_DefaultDesign2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_DefaultDesign> TSql_DefaultDesign3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_DefaultDesign> TSql_DefaultDesign4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_DefaultDesign> TSql_DefaultDesign5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_DesignCamera> TSql_DesignCamera { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_DesignCamera> TSql_DesignCamera1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_DesignDetails> TSql_DesignDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_DesignDetails> TSql_DesignDetails1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_Employee> TSql_Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_Employee> TSql_Employee1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_Employee> TSql_Employee2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_Register> TSql_Register { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_Register> TSql_Register1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tsql_RemplaceArticleStok> Tsql_RemplaceArticleStok { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tsql_RemplaceArticleStok> Tsql_RemplaceArticleStok1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tsql_RemplaceArticleStokChildren> Tsql_RemplaceArticleStokChildren { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tsql_RemplaceArticleStokChildren> Tsql_RemplaceArticleStokChildren1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_Roles> TSql_Roles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_Roles> TSql_Roles1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_System> TSql_System { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_System> TSql_System1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_TapeInialEndWallIMoreThan300> TSql_TapeInialEndWallIMoreThan300 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_TapeInialEndWallIMoreThan300> TSql_TapeInialEndWallIMoreThan3001 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_TapeInialEndWallIMoreThan300> TSql_TapeInialEndWallIMoreThan3002 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_TapeInialEndWallIsLessThan300> TSql_TapeInialEndWallIsLessThan300 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_TapeInialEndWallIsLessThan300> TSql_TapeInialEndWallIsLessThan3001 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_TemporalList> TSql_TemporalList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_TemporalList> TSql_TemporalList1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_Help> TSql_Help { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_Help> TSql_Help1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_HelpGrup> TSql_HelpGrup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_HelpGrup> TSql_HelpGrup1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_TotalListsDesing> TSql_TotalListsDesing { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_TotalListsDesing> TSql_TotalListsDesing1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_ConfigDesingDefault> TSql_ConfigDesingDefault { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_ConfigDesingDefault> TSql_ConfigDesingDefault1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_ConfigDesing> TSql_ConfigDesing { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_ConfigDesing> TSql_ConfigDesing1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_ConfigDesing> TSql_ConfigDesing2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_Design> TSql_Design { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_Design> TSql_Design1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_RollGrupDesing> TSql_RollGrupDesing { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_RollGrupDesing> TSql_RollGrupDesing1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_RollFunctionsUser> TSql_RollFunctionsUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_RollFunctionsUser> TSql_RollFunctionsUser1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_User_Roles> TSql_User_Roles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_User_Roles> TSql_User_Roles1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_User_Roles> TSql_User_Roles2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tsql_Master_Articles> Tsql_Master_Articles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tsql_Master_Articles> Tsql_Master_Articles1 { get; set; }
    }
}
