//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ConexionData : DbContext
    {
        public ConexionData()
            : base("name=ConexionData")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TSql_Countrys> TSql_Countrys { get; set; }
        public virtual DbSet<TSql_DesignCamera> TSql_DesignCamera { get; set; }
        public virtual DbSet<TSql_System> TSql_System { get; set; }
        public virtual DbSet<TSql_App> TSql_App { get; set; }
        public virtual DbSet<TSql_Register> TSql_Register { get; set; }
        public virtual DbSet<Tsql_RemplaceArticleStok> Tsql_RemplaceArticleStok { get; set; }
        public virtual DbSet<Tsql_RemplaceArticleStokChildren> Tsql_RemplaceArticleStokChildren { get; set; }
        public virtual DbSet<TSql_TapeInialEndWallIMoreThan300> TSql_TapeInialEndWallIMoreThan300 { get; set; }
        public virtual DbSet<TSql_TapeInialEndWallIsLessThan300> TSql_TapeInialEndWallIsLessThan300 { get; set; }
        public virtual DbSet<TSql_Roles> TSql_Roles { get; set; }
        public virtual DbSet<TSql_Company> TSql_Company { get; set; }
        public virtual DbSet<TSql_TemporalList> TSql_TemporalList { get; set; }
        public virtual DbSet<TSql_Branch> TSql_Branch { get; set; }
        public virtual DbSet<TSql_DefaultDesign> TSql_DefaultDesign { get; set; }
        public virtual DbSet<TSql_DesignDetails> TSql_DesignDetails { get; set; }
        public virtual DbSet<TSql_Employee> TSql_Employee { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<TSql_Help> TSql_Help { get; set; }
        public virtual DbSet<TSql_HelpGrup> TSql_HelpGrup { get; set; }
        public virtual DbSet<TSql_TotalListsDesing> TSql_TotalListsDesing { get; set; }
        public virtual DbSet<TSql_ConfigDesingDefault> TSql_ConfigDesingDefault { get; set; }
        public virtual DbSet<TSql_ConfigDesing> TSql_ConfigDesing { get; set; }
        public virtual DbSet<TSql_Design> TSql_Design { get; set; }
        public virtual DbSet<TSql_RollGrupDesing> TSql_RollGrupDesing { get; set; }
        public virtual DbSet<TSql_RollFunctionsUser> TSql_RollFunctionsUser { get; set; }
        public virtual DbSet<TSql_User_Roles> TSql_User_Roles { get; set; }
        public virtual DbSet<Tsql_Master_Articles> Tsql_Master_Articles { get; set; }
    }
}
