//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tsql_RemplaceArticleStok
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tsql_RemplaceArticleStok()
        {
            this.Tsql_RemplaceArticleStokChildren = new HashSet<Tsql_RemplaceArticleStokChildren>();
            this.Tsql_RemplaceArticleStokChildren1 = new HashSet<Tsql_RemplaceArticleStokChildren>();
        }
    
        public long IdObject { get; set; }
        public string LinkAspNetUsers { get; set; }
        public string LinkUserCreate { get; set; }
        public long LinkMaster_Articles { get; set; }
        public System.DateTime AddDateMade { get; set; }
        public string LinkUserChangeBy { get; set; }
        public System.DateTime AddLastDateChange { get; set; }
        public long Ntimeschanged { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tsql_RemplaceArticleStokChildren> Tsql_RemplaceArticleStokChildren { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tsql_RemplaceArticleStokChildren> Tsql_RemplaceArticleStokChildren1 { get; set; }
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual AspNetUsers AspNetUsers1 { get; set; }
    }
}
