//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSql_Help
    {
        public long SysObjectID { get; set; }
        public string AddHelp { get; set; }
        public string AddHelpContent { get; set; }
        public string LinkVideo { get; set; }
        public long LinkHelpGroup { get; set; }
        public Nullable<long> LinkNexAddHelp { get; set; }
        public Nullable<long> LinkPreviousAddHelp { get; set; }
        public string LinkMadeBy { get; set; }
        public string LinkChangeBy { get; set; }
        public System.DateTime AddDateMade { get; set; }
        public System.DateTime AddLastDateChange { get; set; }
        public string AddImage { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual AspNetUsers AspNetUsers1 { get; set; }
        public virtual TSql_HelpGrup TSql_HelpGrup { get; set; }
    }
}
