//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSql_Client_V2
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TSql_Client_V2()
        {
            this.TSql_Jobside = new HashSet<TSql_Jobside>();
            this.TSql_Document = new HashSet<TSql_Document>();
            this.TSql_Offers = new HashSet<TSql_Offers>();
        }
    
        public long IdObject { get; set; }
        public string TextLabel { get; set; }
        public bool Is_Delete { get; set; }
        public bool Is_Active { get; set; }
        public string LinkMadeBy { get; set; }
        public string LinModifiedBy { get; set; }
        public System.DateTime AddDateMade { get; set; }
        public Nullable<System.DateTime> AddLastDateChange { get; set; }
        public long Ntimeschanged { get; set; }
        public Nullable<long> LinkMethodOfPayment { get; set; }
        public string Path_Ico { get; set; }
        public string Path_Logo { get; set; }
        public string TextCode { get; set; }
        public string TextTaxId { get; set; }
        public string TextEmail { get; set; }
        public string TextPhone { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual AspNetUsers AspNetUsers1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_Jobside> TSql_Jobside { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_Document> TSql_Document { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_Offers> TSql_Offers { get; set; }
    }
}
