//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSql_DesignWall
    {
        public long IdObject { get; set; }
        public string TextLabel { get; set; }
        public long LinkDesign_V2 { get; set; }
        public string TextClientWallId { get; set; }
        public Nullable<long> NumberLineId { get; set; }
        public Nullable<long> NumberWallGroupId { get; set; }
        public Nullable<long> NumberPolylineGroupId { get; set; }
        public string TextWallRole { get; set; }
        public Nullable<long> NumberLinkOffsetFromLineId { get; set; }
        public Nullable<double> NumberOffsetMm { get; set; }
        public Nullable<double> NumberWallFaceSideSign { get; set; }
        public string TextSystem { get; set; }
        public double NumberP1X { get; set; }
        public double NumberP1Y { get; set; }
        public double NumberP1Z { get; set; }
        public double NumberP2X { get; set; }
        public double NumberP2Y { get; set; }
        public double NumberP2Z { get; set; }
        public Nullable<double> NumberDrawP1X { get; set; }
        public Nullable<double> NumberDrawP1Y { get; set; }
        public Nullable<double> NumberDrawP1Z { get; set; }
        public Nullable<double> NumberDrawP2X { get; set; }
        public Nullable<double> NumberDrawP2Y { get; set; }
        public Nullable<double> NumberDrawP2Z { get; set; }
        public string TextTypeMesh { get; set; }
        public Nullable<double> NumberLong { get; set; }
        public Nullable<double> NumberWidth { get; set; }
        public Nullable<double> NumberHeight { get; set; }
        public Nullable<double> NumberXRotation { get; set; }
        public Nullable<double> NumberYRotation { get; set; }
        public Nullable<double> NumberZRotation { get; set; }
        public Nullable<double> NumberXCoordinate { get; set; }
        public Nullable<double> NumberYCoordinate { get; set; }
        public Nullable<double> NumberZCoordinate { get; set; }
        public bool Is_Formwork { get; set; }
        public bool Is_UniversalPanel { get; set; }
        public string TextTape_1 { get; set; }
        public string TextTape_2 { get; set; }
        public string TextIdConnection_1 { get; set; }
        public string TextIdConnection_2 { get; set; }
        public bool Is_CheckBracketInside { get; set; }
        public bool Is_CheckBracketOutside { get; set; }
        public bool Is_CheckRijiInside { get; set; }
        public bool Is_CheckRijiOutside { get; set; }
        public bool Is_CheckPropInside { get; set; }
        public bool Is_CheckPropOutside { get; set; }
        public bool Is_CheckPropInsideInf { get; set; }
        public bool Is_CheckPropOutsideInf { get; set; }
        public string TextTape_0 { get; set; }
        public string TextTape_90 { get; set; }
        public string TextTape_180 { get; set; }
        public string TextTape_270 { get; set; }
        public string TextTypeWall { get; set; }
        public string TextTypeWallLeft { get; set; }
        public string TextTypeWallRight { get; set; }
        public string TextTypeWall_0 { get; set; }
        public string TextTypeWall_90 { get; set; }
        public string TextTypeWall_180 { get; set; }
        public string TextTypeWall_270 { get; set; }
        public string TextSubLong_0 { get; set; }
        public string TextSubLong_90 { get; set; }
        public string TextSubLong_180 { get; set; }
        public string TextSubLong_270 { get; set; }
        public string TextIdWall_0 { get; set; }
        public string TextIdWall_90 { get; set; }
        public string TextIdWall_180 { get; set; }
        public string TextIdWall_270 { get; set; }
        public string TextGroup { get; set; }
        public bool Is_PilarType { get; set; }
        public bool Is_FormworkMode { get; set; }
        public bool Is_Panel060 { get; set; }
        public bool Is_CheckDimWall { get; set; }
        public bool Is_Check750R { get; set; }
        public bool Is_SolutionCornerXUniversalPanelCorner { get; set; }
        public bool Is_SolutionCornerYUniversalPanelCorner { get; set; }
        public Nullable<int> NumberRemate_0 { get; set; }
        public Nullable<int> NumberRemate_90 { get; set; }
        public Nullable<int> NumberRemate_180 { get; set; }
        public Nullable<int> NumberRemate_270 { get; set; }
        public Nullable<double> NumberRematePositionX { get; set; }
        public Nullable<double> NumberRematePositionXMirror { get; set; }
        public Nullable<double> NumberRematePosition90Y { get; set; }
        public Nullable<double> NumberRematePosition90YMirror { get; set; }
        public Nullable<double> NumberRematePosition180X { get; set; }
        public Nullable<double> NumberRematePosition180XMirror { get; set; }
        public Nullable<double> NumberRematePosition270Y { get; set; }
        public Nullable<double> NumberRematePosition270YMirror { get; set; }
        public Nullable<long> NumberLongLeft { get; set; }
        public Nullable<long> NumberLongRight { get; set; }
        public Nullable<long> NumberInitialWall { get; set; }
        public Nullable<long> NumberEndWall { get; set; }
        public Nullable<long> NumberIdCornerDown { get; set; }
        public Nullable<long> NumberIdCornerLeft { get; set; }
        public Nullable<long> NumberScaleEsqY { get; set; }
        public bool Is_Delete { get; set; }
        public bool Is_Active { get; set; }
        public string LinkMadeBy { get; set; }
        public string LinModifiedBy { get; set; }
        public System.DateTime AddDateMade { get; set; }
        public Nullable<System.DateTime> AddLastDateChange { get; set; }
        public long Ntimeschanged { get; set; }
    
        public virtual TSql_Design_V2 TSql_Design_V2 { get; set; }
    }
}
