//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSql_TotalListsDesing
    {
        public long IdObject { get; set; }
        public string LinkMadeBy { get; set; }
        public System.DateTime AddDateMade { get; set; }
        public string AddChangeBy { get; set; }
        public System.DateTime AddLastDateChange { get; set; }
        public long AddTotalArticles { get; set; }
        public long AddTotalWeight { get; set; }
        public long AddTotalM2 { get; set; }
        public long LinkDesing { get; set; }
        public long AddNumberSendMail { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual AspNetUsers AspNetUsers1 { get; set; }
        public virtual TSql_Design TSql_Design { get; set; }
    }
}
