//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSql_Plantilla
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TSql_Plantilla()
        {
            this.TSql_Employee = new HashSet<TSql_Employee>();
        }
    
        public long SysObjectID { get; set; }
        public string AttName { get; set; }
        public string AttColor { get; set; }
        public string AttLogo { get; set; }
        public string AttFavicon { get; set; }
        public bool AttIsDefault { get; set; }
        public bool AttIsDeleted { get; set; }
        public string LinCreatedBy { get; set; }
        public System.DateTime AttCreated { get; set; }
        public string LinModifiedBy { get; set; }
        public System.DateTime AttLastModification { get; set; }
        public long SysUpdateNumber { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_Employee> TSql_Employee { get; set; }
    }
}
