//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSql_Offers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TSql_Offers()
        {
            this.TSql_Document = new HashSet<TSql_Document>();
        }
    
        public long IdObject { get; set; }
        public string AddOfferNumber { get; set; }
        public string TextLabel { get; set; }
        public string AddDescription { get; set; }
        public long LinkJobside { get; set; }
        public long LinkClient_V2 { get; set; }
        public bool Is_Delete { get; set; }
        public bool Is_Active { get; set; }
        public string LinkMadeBy { get; set; }
        public string LinModifiedBy { get; set; }
        public System.DateTime AddDateMade { get; set; }
        public string AddChangeBy { get; set; }
        public long Ntimeschanged { get; set; }
        public long LinkOfferState { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual AspNetUsers AspNetUsers1 { get; set; }
        public virtual TSql_Client_V2 TSql_Client_V2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_Document> TSql_Document { get; set; }
        public virtual TSql_OfferState TSql_OfferState { get; set; }
        public virtual TSql_Jobside TSql_Jobside { get; set; }
    }
}
