//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSql_Design_V2
    {
        public long SysObjectID { get; set; }
        public string AttLabel { get; set; }
        public string AttDescription { get; set; }
        public double AttCenterY { get; set; }
        public double AttCenterX { get; set; }
        public System.DateTime AttCreated { get; set; }
        public bool AttIsDeleted { get; set; }
        public string AttThumbnail { get; set; }
        public long AttActiveCameraType { get; set; }
        public string LinCreatedBy { get; set; }
        public string LinModifiedBy { get; set; }
        public long SysUpdateNumber { get; set; }
        public bool ItIsShared { get; set; }
        public bool ItIsSharedMyGrup { get; set; }
        public System.DateTime AttChange { get; set; }
        public bool IsRenderAt60 { get; set; }
        public long LinkOffers { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual AspNetUsers AspNetUsers1 { get; set; }
        public virtual TSql_Offers TSql_Offers { get; set; }
    }
}
