//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tsql_RemplaceArticleStokChildren
    {
        public long IdObject { get; set; }
        public long LinkRemplaceArticleStok { get; set; }
        public long LinkMaster_Articles { get; set; }
        public string LinkUserCreate { get; set; }
        public System.DateTime AddDateMade { get; set; }
        public string LinkUserChangeBy { get; set; }
        public System.DateTime AddLastDateChange { get; set; }
        public long Ntimeschanged { get; set; }
    
        public virtual Tsql_RemplaceArticleStok Tsql_RemplaceArticleStok { get; set; }
        public virtual Tsql_RemplaceArticleStok Tsql_RemplaceArticleStok1 { get; set; }
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual AspNetUsers AspNetUsers1 { get; set; }
    }
}
