//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSql_ConfigDesing
    {
        public long SysObjectID { get; set; }
        public double AttAttWeightImportantJobsite { get; set; }
        public string LinkMadeBy { get; set; }
        public string LinkChangeBy { get; set; }
        public System.DateTime AddDateMade { get; set; }
        public System.DateTime AddLastDateChange { get; set; }
        public long SysUpdateNumber { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual AspNetUsers AspNetUsers1 { get; set; }
        public virtual AspNetUsers AspNetUsers2 { get; set; }
    }
}
