//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSql_Employee
    {
        public long SysObjectID { get; set; }
        public string AttName { get; set; }
        public string AttSurname { get; set; }
        public string AttPhoto { get; set; }
        public string AttPhotoMenu { get; set; }
        public string LinCreatedBy { get; set; }
        public System.DateTime AttCreated { get; set; }
        public string LinModifiedBy { get; set; }
        public System.DateTime AttLastModification { get; set; }
        public long LinCompany { get; set; }
        public long LinBusiness { get; set; }
        public long SysUpdateNumber { get; set; }
        public string LinAspNetUsert { get; set; }
        public bool AttIsDeleted { get; set; }
        public Nullable<long> Linlanguage { get; set; }
        public string AttPassAspNetUsert { get; set; }
    
        public virtual TSql_Company TSql_Company { get; set; }
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual AspNetUsers AspNetUsers1 { get; set; }
        public virtual AspNetUsers AspNetUsers2 { get; set; }
    }
}
