//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSql_Jobside
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TSql_Jobside()
        {
            this.TSql_Document = new HashSet<TSql_Document>();
            this.TSql_Offers = new HashSet<TSql_Offers>();
        }
    
        public long IdObject { get; set; }
        public string AddNJobside { get; set; }
        public string AddNJobsideClient { get; set; }
        public string TextLabel { get; set; }
        public bool Is_Delete { get; set; }
        public bool Is_Active { get; set; }
        public string LinkMadeBy { get; set; }
        public string LinModifiedBy { get; set; }
        public System.DateTime AddDateMade { get; set; }
        public Nullable<System.DateTime> AddLastDateChange { get; set; }
        public long Ntimeschanged { get; set; }
        public Nullable<long> LinkClient_V2 { get; set; }
        public bool BitBillSameAsLoc { get; set; }
        public string Loc_Place_Id { get; set; }
        public string Loc_Formatted_Address { get; set; }
        public Nullable<decimal> Loc_Lat { get; set; }
        public Nullable<decimal> Loc_Lng { get; set; }
        public string Loc_Street_Number { get; set; }
        public string Loc_Route { get; set; }
        public string Loc_Subpremise { get; set; }
        public string Loc_Locality { get; set; }
        public string Loc_Admin_Area_1 { get; set; }
        public string Loc_Admin_Area_2 { get; set; }
        public string Loc_Postal_Code { get; set; }
        public string Loc_Country_Code { get; set; }
        public string Loc_Country_Name { get; set; }
        public string Loc_Address_Components_Json { get; set; }
        public string Bill_Place_Id { get; set; }
        public string Bill_Formatted_Address { get; set; }
        public Nullable<decimal> Bill_Lat { get; set; }
        public Nullable<decimal> Bill_Lng { get; set; }
        public string Bill_Street_Number { get; set; }
        public string Bill_Route { get; set; }
        public string Bill_Subpremise { get; set; }
        public string Bill_Locality { get; set; }
        public string Bill_Admin_Area_1 { get; set; }
        public string Bill_Admin_Area_2 { get; set; }
        public string Bill_Postal_Code { get; set; }
        public string Bill_Country_Code { get; set; }
        public string Bill_Country_Name { get; set; }
        public string Bill_Address_Components_Json { get; set; }
        public string TextContractRef { get; set; }
        public string TextJobsideNotes { get; set; }
        public long LinBranch { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual AspNetUsers AspNetUsers1 { get; set; }
        public virtual TSql_Branch TSql_Branch { get; set; }
        public virtual TSql_Client_V2 TSql_Client_V2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_Document> TSql_Document { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_Offers> TSql_Offers { get; set; }
    }
}
