//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSql_TapeInialEndWallIsLessThan300
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TSql_TapeInialEndWallIsLessThan300()
        {
            this.TSql_DefaultDesign = new HashSet<TSql_DefaultDesign>();
        }
    
        public long IdObject { get; set; }
        public string AddTapeWall { get; set; }
        public string LinkMadeBy { get; set; }
        public string LinModifiedBy { get; set; }
        public System.DateTime AddDateMade { get; set; }
        public string AddChangeBy { get; set; }
        public long Ntimeschanged { get; set; }
        public string AddImage { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_DefaultDesign> TSql_DefaultDesign { get; set; }
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual AspNetUsers AspNetUsers1 { get; set; }
    }
}
