//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSql_Design
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TSql_Design()
        {
            this.TSql_DesignCamera = new HashSet<TSql_DesignCamera>();
            this.TSql_DesignDetails = new HashSet<TSql_DesignDetails>();
            this.TSql_TotalListsDesing = new HashSet<TSql_TotalListsDesing>();
        }
    
        public long SysObjectID { get; set; }
        public string AttLabel { get; set; }
        public string AttDescription { get; set; }
        public double AttCenterY { get; set; }
        public double AttCenterX { get; set; }
        public System.DateTime AttCreated { get; set; }
        public bool AttIsDeleted { get; set; }
        public string AttThumbnail { get; set; }
        public long AttActiveCameraType { get; set; }
        public string LinCreatedBy { get; set; }
        public string LinModifiedBy { get; set; }
        public long SysUpdateNumber { get; set; }
        public bool ItIsShared { get; set; }
        public bool ItIsSharedMyGrup { get; set; }
        public System.DateTime AttChange { get; set; }
        public bool IsRenderAt60 { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual AspNetUsers AspNetUsers1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_DesignCamera> TSql_DesignCamera { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_DesignDetails> TSql_DesignDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_TotalListsDesing> TSql_TotalListsDesing { get; set; }
    }
}
