//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSql_HelpGrup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TSql_HelpGrup()
        {
            this.TSql_Help = new HashSet<TSql_Help>();
        }
    
        public long IdObject { get; set; }
        public long LinkHelp { get; set; }
        public string AddIcon { get; set; }
        public string AddHelpGrup { get; set; }
        public string AddHelpContent { get; set; }
        public string LinkMadeBy { get; set; }
        public string LinkChangeBy { get; set; }
        public System.DateTime AddDateMade { get; set; }
        public System.DateTime AddLastDateChange { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual AspNetUsers AspNetUsers1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_Help> TSql_Help { get; set; }
    }
}
