//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSql_DefaultDesign
    {
        public long IdObject { get; set; }
        public string LinkAspNetUsers { get; set; }
        public double NumberClosingStartEndWall { get; set; }
        public double NumberWallheigh { get; set; }
        public double NumberwallWidth { get; set; }
        public double NumberwallLength { get; set; }
        public string LinkMadeBy { get; set; }
        public string LinModifiedBy { get; set; }
        public System.DateTime AddDateMade { get; set; }
        public string AddChangeBy { get; set; }
        public System.DateTime AddLastDateChange { get; set; }
        public long Ntimeschanged { get; set; }
        public bool BitIsDeleted { get; set; }
        public long LinkEnvironment { get; set; }
        public bool ExitingPanel2400 { get; set; }
        public long LinTapeInialEndWallIsLessThan300 { get; set; }
        public long LinTapeInialEndWallIMoreThan300 { get; set; }
        public bool AddTapeWidthExactIfPossible { get; set; }
        public bool IsSolutionCornerWithUniversalPanel { get; set; }
        public long OrbitControlsType { get; set; }
    
        public virtual TSql_TapeInialEndWallIMoreThan300 TSql_TapeInialEndWallIMoreThan300 { get; set; }
        public virtual TSql_TapeInialEndWallIsLessThan300 TSql_TapeInialEndWallIsLessThan300 { get; set; }
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual AspNetUsers AspNetUsers1 { get; set; }
        public virtual AspNetUsers AspNetUsers2 { get; set; }
        public virtual AspNetUsers AspNetUsers3 { get; set; }
        public virtual AspNetUsers AspNetUsers4 { get; set; }
        public virtual AspNetUsers AspNetUsers5 { get; set; }
    }
}
