//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tsql_Master_Articles
    {
        public long IdObject { get; set; }
        public string AddAtenkoCode { get; set; }
        public string TextCode { get; set; }
        public string TextLabel { get; set; }
        public Nullable<double> NumberHigh { get; set; }
        public Nullable<double> NumberWidth { get; set; }
        public Nullable<double> NumberLong { get; set; }
        public Nullable<double> NumberWeight { get; set; }
        public string TextBlockNumber { get; set; }
        public string TextStlNumber { get; set; }
        public string TextColor1 { get; set; }
        public string TextColor2 { get; set; }
        public Nullable<double> NumberMts2 { get; set; }
        public Nullable<double> NumberMts3 { get; set; }
        public string LinkMadeBy { get; set; }
        public System.DateTime AddDateMade { get; set; }
        public string AddChangeBy { get; set; }
        public System.DateTime AddLastDateChange { get; set; }
        public long Ntimeschanged { get; set; }
        public bool AddIsActive { get; set; }
        public long LinkSystem { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual AspNetUsers AspNetUsers1 { get; set; }
        public virtual TSql_System TSql_System { get; set; }
    }
}
