//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSql_TelegramDesignInbox
    {
        public long SysObjectID { get; set; }
        public long LinDesign { get; set; }
        public string TelegramMessageId { get; set; }
        public string TelegramChatId { get; set; }
        public string TelegramUserId { get; set; }
        public string TelegramUserName { get; set; }
        public string Caption { get; set; }
        public string FileId { get; set; }
        public string FileUniqueId { get; set; }
        public Nullable<int> WidthPx { get; set; }
        public Nullable<int> HeightPx { get; set; }
        public string Estado { get; set; }
        public System.DateTime FechaMensajeUtc { get; set; }
        public System.DateTime FechaRegistroUtc { get; set; }
    
        public virtual TSql_Design TSql_Design { get; set; }
    }
}
