//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSql_DesignCamera
    {
        public long SysObjectID { get; set; }
        public string LinUser { get; set; }
        public long LinDesaing { get; set; }
        public long AttCameraType { get; set; }
        public double AttPositionX { get; set; }
        public double AttPositionY { get; set; }
        public double AttPositionZ { get; set; }
        public double AttTargetX { get; set; }
        public double AttTargetY { get; set; }
        public double AttTargetZ { get; set; }
        public System.DateTime AttLastModification { get; set; }
        public double AttZoom { get; set; }
        public bool AttIsActive { get; set; }
        public string LinModifiedBy { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual AspNetUsers AspNetUsers1 { get; set; }
        public virtual TSql_Design TSql_Design { get; set; }
    }
}
