//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSql_RollGrupDesing
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TSql_RollGrupDesing()
        {
            this.TSql_RollFunctionsUser = new HashSet<TSql_RollFunctionsUser>();
        }
    
        public long SysObjectID { get; set; }
        public string LinkMadeBy { get; set; }
        public string LinkChangeBy { get; set; }
        public System.DateTime AddDateMade { get; set; }
        public System.DateTime AddLastDateChange { get; set; }
        public long SysUpdateNumber { get; set; }
        public string AttGrupDesing { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual AspNetUsers AspNetUsers1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_RollFunctionsUser> TSql_RollFunctionsUser { get; set; }
    }
}
