//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSql_RolesFuntionUser
    {
        public long SysObjectID { get; set; }
        public long LinRollFunctions { get; set; }
        public string LinAspNetUsers { get; set; }
        public string LinCreatedBy { get; set; }
        public string LinModifiedBy { get; set; }
        public System.DateTime AttCreated { get; set; }
        public System.DateTime AttLastModification { get; set; }
        public long SysUpdateNumber { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual AspNetUsers AspNetUsers1 { get; set; }
    }
}
