//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSql_Roles
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TSql_Roles()
        {
            this.TSql_RollFunctionsUser = new HashSet<TSql_RollFunctionsUser>();
            this.TSql_User_Roles = new HashSet<TSql_User_Roles>();
        }
    
        public long SysObjectID { get; set; }
        public string AttLabel { get; set; }
        public string AttDescription { get; set; }
        public string LinCreatedBy { get; set; }
        public System.DateTime AttCreated { get; set; }
        public string LinModifiedBy { get; set; }
        public System.DateTime AttLastModification { get; set; }
        public long SysUpdateNumber { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual AspNetUsers AspNetUsers1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_RollFunctionsUser> TSql_RollFunctionsUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_User_Roles> TSql_User_Roles { get; set; }
    }
}
