//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSql_DesignDetails
    {
        public long IdObject { get; set; }
        public long LinDesaing { get; set; }
        public string LinModifiedBy { get; set; }
        public System.DateTime AddDateMade { get; set; }
        public string AddChangeBy { get; set; }
        public long Ntimeschanged { get; set; }
        public Nullable<double> AddPositionX { get; set; }
        public Nullable<double> AddPositionY { get; set; }
        public Nullable<double> AddPositionZ { get; set; }
        public string IdWall { get; set; }
        public Nullable<double> AddRotationX { get; set; }
        public Nullable<double> AddRotationY { get; set; }
        public Nullable<double> AddRotationZ { get; set; }
        public string AddName { get; set; }
        public Nullable<double> AddScaleX { get; set; }
        public Nullable<double> AddScaleY { get; set; }
        public Nullable<double> AddScaleZ { get; set; }
        public Nullable<long> AddIniciall_Wall { get; set; }
        public Nullable<long> AddEnd_Wall { get; set; }
        public string AddTypeWall { get; set; }
        public string AddTypeWallLeft { get; set; }
        public string AddTypeWallRight { get; set; }
        public Nullable<long> IDCornerDown { get; set; }
        public Nullable<long> IDCornerLeft { get; set; }
        public Nullable<long> ScaleEsqy { get; set; }
        public Nullable<bool> CHeckDimWall { get; set; }
        public Nullable<bool> CHeckBracketInside { get; set; }
        public Nullable<bool> CHeckBracketOutside { get; set; }
        public Nullable<bool> CHeckRijiInside { get; set; }
        public Nullable<bool> CHeckRijiOutside { get; set; }
        public Nullable<bool> CHeckPropInside { get; set; }
        public Nullable<bool> CHeckPropOutside { get; set; }
        public Nullable<bool> CHeckPropInsideInf { get; set; }
        public Nullable<bool> CHeckPropOutsideInf { get; set; }
        public Nullable<bool> CHeck750R { get; set; }
        public Nullable<long> LongLeft { get; set; }
        public Nullable<long> LongRight { get; set; }
        public Nullable<bool> IsSolutionCornerYUniversalPanelCorner { get; set; }
        public Nullable<bool> IsSolutionCornerXUniversalPanelCorner { get; set; }
        public string AddTape_0 { get; set; }
        public string AddTape_180 { get; set; }
        public string AddTape_90 { get; set; }
        public string AddTape_270 { get; set; }
        public string AddGrup { get; set; }
        public Nullable<bool> IsPilarType { get; set; }
        public string TypeWall_0 { get; set; }
        public string TypeWall_180 { get; set; }
        public string TypeWall_90 { get; set; }
        public string TypeWall_270 { get; set; }
        public string Sub_Long_0 { get; set; }
        public string Sub_Long_180 { get; set; }
        public string Sub_Long_90 { get; set; }
        public string Sub_Long_270 { get; set; }
        public string IdWall_0 { get; set; }
        public string IdWall_180 { get; set; }
        public string IdWall_90 { get; set; }
        public string IdWall_270 { get; set; }
        public bool IdTypeFormworkMode { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual AspNetUsers AspNetUsers1 { get; set; }
        public virtual TSql_Design TSql_Design { get; set; }
    }
}
