//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSql_Branch
    {
        public long SysObjectID { get; set; }
        public string AttLabel { get; set; }
        public string AttDescription { get; set; }
        public string LinCreatedBy { get; set; }
        public System.DateTime AttCreated { get; set; }
        public string LinModifiedBy { get; set; }
        public System.DateTime AttLastModification { get; set; }
        public long SysUpdateNumber { get; set; }
        public long LinCompany { get; set; }
        public long LinBusiness { get; set; }
    
        public virtual TSql_Company TSql_Company { get; set; }
    }
}
