//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSql_PluginDeviceAuth
    {
        public long SysObjectID { get; set; }
        public string DeviceId { get; set; }
        public string LinAspNetUsert { get; set; }
        public string MachineName { get; set; }
        public string UsuarioWindows { get; set; }
        public string PluginVersion { get; set; }
        public bool Allowed { get; set; }
        public bool IsActive { get; set; }
        public bool IsRevoked { get; set; }
        public string Estado { get; set; }
        public bool AttIsDeleted { get; set; }
        public Nullable<System.DateTime> LastCheckUtc { get; set; }
        public string LinCreatedBy { get; set; }
        public System.DateTime AttCreated { get; set; }
        public string LinModifiedBy { get; set; }
        public System.DateTime AttLastModification { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
    }
}
