//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSql_Help
    {
        public long SysObjectID { get; set; }
        public string AddHelp { get; set; }
        public string AddHelpContent { get; set; }
        public string LinkVideo { get; set; }
        public long LinkHelpGroup { get; set; }
        public Nullable<long> LinkNexAddHelp { get; set; }
        public Nullable<long> LinkPreviousAddHelp { get; set; }
        public string LinkMadeBy { get; set; }
        public string LinkChangeBy { get; set; }
        public System.DateTime AddDateMade { get; set; }
        public System.DateTime AddLastDateChange { get; set; }
        public string AddImage { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual AspNetUsers AspNetUsers1 { get; set; }
        public virtual TSql_HelpGrup TSql_HelpGrup { get; set; }
    }
}
