//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSql_Countrys
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TSql_Countrys()
        {
            this.TSql_Company = new HashSet<TSql_Company>();
        }
    
        public long IdObject { get; set; }
        public string TextLabel { get; set; }
        public string TextIso3 { get; set; }
        public string TextIso2 { get; set; }
        public string NumberIso { get; set; }
        public string TextFlag { get; set; }
        public string LinkMadeBy { get; set; }
        public System.DateTime AddDateMade { get; set; }
        public string LinkChangeBy { get; set; }
        public System.DateTime AddLastDateChange { get; set; }
        public long Ntimeschanged { get; set; }
        public bool AddIsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_Company> TSql_Company { get; set; }
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual AspNetUsers AspNetUsers1 { get; set; }
    }
}
