//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSql_Document
    {
        public long IdObject { get; set; }
        public string AddDescription { get; set; }
        public Nullable<long> LinkJobside { get; set; }
        public Nullable<long> LinkClient_V2 { get; set; }
        public Nullable<long> LinkOffer { get; set; }
        public Nullable<long> LinkPersonal { get; set; }
        public Nullable<long> LinkExtension { get; set; }
        public long LinkDocumentType { get; set; }
        public string AddPath { get; set; }
        public bool Is_Delete { get; set; }
        public bool Is_Active { get; set; }
        public string LinkMadeBy { get; set; }
        public string LinModifiedBy { get; set; }
        public System.DateTime AddDateMade { get; set; }
        public string AddChangeBy { get; set; }
        public long Ntimeschanged { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public Nullable<System.DateTime> NoticeDate { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual AspNetUsers AspNetUsers1 { get; set; }
        public virtual TSql_Client_V2 TSql_Client_V2 { get; set; }
        public virtual TSql_DocumentType TSql_DocumentType { get; set; }
        public virtual TSql_DocumentTypeExtension TSql_DocumentTypeExtension { get; set; }
        public virtual TSql_Jobside TSql_Jobside { get; set; }
        public virtual TSql_Offers TSql_Offers { get; set; }
    }
}
