//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSql_Company
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TSql_Company()
        {
            this.TSql_Branch = new HashSet<TSql_Branch>();
            this.TSql_Employee = new HashSet<TSql_Employee>();
        }
    
        public long SysObjectID { get; set; }
        public string AddLeter { get; set; }
        public string TextLabel { get; set; }
        public string TextDescription { get; set; }
        public string LinkMadeBy { get; set; }
        public System.DateTime AddDateMade { get; set; }
        public string AddChangeBy { get; set; }
        public System.DateTime AddLastDateChange { get; set; }
        public long Ntimeschanged { get; set; }
        public bool BitIsDeleted { get; set; }
        public string TextLogo { get; set; }
        public string TextCoordinates { get; set; }
        public string TextAddress_1 { get; set; }
        public string TextAddress_2 { get; set; }
        public Nullable<int> TextPostal_Code { get; set; }
        public string TextTown_1 { get; set; }
        public string TextTown_2 { get; set; }
        public Nullable<long> LinkCountry { get; set; }
    
        public virtual TSql_Countrys TSql_Countrys { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_Branch> TSql_Branch { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_Employee> TSql_Employee { get; set; }
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual AspNetUsers AspNetUsers1 { get; set; }
        public virtual AspNetUsers AspNetUsers2 { get; set; }
        public virtual AspNetUsers AspNetUsers3 { get; set; }
    }
}
