//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSql_TelegramDesignAccess
    {
        public long SysObjectID { get; set; }
        public long LinDesign { get; set; }
        public string TelegramChatId { get; set; }
        public string TelegramUserId { get; set; }
        public string Alias { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime FechaRegistroUtc { get; set; }
    
        public virtual TSql_Design TSql_Design { get; set; }
    }
}
