//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSql_DesignWallArticle
    {
        public long IdObject { get; set; }
        public string TextLabel { get; set; }
        public long LinkDesign_V2 { get; set; }
        public long LinkDesignWall { get; set; }
        public Nullable<long> LinkMasterArticle { get; set; }
        public string TextCode { get; set; }
        public string TextView { get; set; }
        public long NumberSequence { get; set; }
        public double NumberInsertX { get; set; }
        public double NumberInsertY { get; set; }
        public double NumberInsertZ { get; set; }
        public double NumberXRotation { get; set; }
        public double NumberYRotation { get; set; }
        public double NumberZRotation { get; set; }
        public string TextHandleCad { get; set; }
        public bool Is_Delete { get; set; }
        public bool Is_Active { get; set; }
        public string LinkMadeBy { get; set; }
        public string LinModifiedBy { get; set; }
        public System.DateTime AddDateMade { get; set; }
        public Nullable<System.DateTime> AddLastDateChange { get; set; }
        public long Ntimeschanged { get; set; }
    
        public virtual TSql_Design_V2 TSql_Design_V2 { get; set; }
        public virtual TSql_DesignWall TSql_DesignWall { get; set; }
        public virtual Tsql_Master_Articles Tsql_Master_Articles { get; set; }
    }
}
