//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tsql_RemplaceArticleStokChildren
    {
        public long IdObject { get; set; }
        public long LinkRemplaceArticleStok { get; set; }
        public long LinkMaster_Articles { get; set; }
        public string LinkUserCreate { get; set; }
        public System.DateTime AddDateMade { get; set; }
        public string LinkUserChangeBy { get; set; }
        public System.DateTime AddLastDateChange { get; set; }
        public long Ntimeschanged { get; set; }
    
        public virtual Tsql_RemplaceArticleStok Tsql_RemplaceArticleStok { get; set; }
        public virtual Tsql_RemplaceArticleStok Tsql_RemplaceArticleStok1 { get; set; }
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual AspNetUsers AspNetUsers1 { get; set; }
    }
}
