//------------------------------------------------------------------------------
// Auto-generated by _gen_branch_resources.js — Branch UI strings (50
// entries).
//------------------------------------------------------------------------------
namespace Desing.Resources
{
    using System;
    using global::System.Globalization;
    using global::System.Resources;

    /// <summary>TSql_Branch module: localized strings (.resx); UICulture desde LanguageUiHelper.</summary>
    public class Branch
    {
        private static ResourceManager resourceMan;
        private static CultureInfo resourceCulture;

        public static ResourceManager ResourceManager =>
            resourceMan ??
            (resourceMan = new global::Desing.Helpers.DbBackedResourceManager(
                "Desing.Resources.Branch", typeof(Branch).Assembly, "Branch"));

        public static CultureInfo Culture
        {
            get => resourceCulture;
            set => resourceCulture = value;
        }
        public static string Aria_CloseModal => ResourceManager.GetString(nameof(Aria_CloseModal), resourceCulture);
        public static string BranchPanel_CreateSectionTitle => ResourceManager.GetString(nameof(BranchPanel_CreateSectionTitle), resourceCulture);
        public static string BranchPanel_New => ResourceManager.GetString(nameof(BranchPanel_New), resourceCulture);
        public static string BranchPanel_Title => ResourceManager.GetString(nameof(BranchPanel_Title), resourceCulture);
        public static string Branch_Btn_BackToCompany => ResourceManager.GetString(nameof(Branch_Btn_BackToCompany), resourceCulture);
        public static string Branch_Btn_OpenFullEdit => ResourceManager.GetString(nameof(Branch_Btn_OpenFullEdit), resourceCulture);
        public static string Branch_Btn_SaveInline => ResourceManager.GetString(nameof(Branch_Btn_SaveInline), resourceCulture);
        public static string Branch_Details_Field_Color => ResourceManager.GetString(nameof(Branch_Details_Field_Color), resourceCulture);
        public static string Branch_Details_Field_Description => ResourceManager.GetString(nameof(Branch_Details_Field_Description), resourceCulture);
        public static string Branch_Details_Field_FormattedAddress => ResourceManager.GetString(nameof(Branch_Details_Field_FormattedAddress), resourceCulture);
        public static string Branch_Details_Field_Letter => ResourceManager.GetString(nameof(Branch_Details_Field_Letter), resourceCulture);
        public static string Branch_Details_Field_Name => ResourceManager.GetString(nameof(Branch_Details_Field_Name), resourceCulture);
        public static string Branch_Details_NoValue => ResourceManager.GetString(nameof(Branch_Details_NoValue), resourceCulture);
        public static string Branch_Err_InvalidCompany => ResourceManager.GetString(nameof(Branch_Err_InvalidCompany), resourceCulture);
        public static string Branch_Err_InvalidData => ResourceManager.GetString(nameof(Branch_Err_InvalidData), resourceCulture);
        public static string Branch_Err_NameRequired => ResourceManager.GetString(nameof(Branch_Err_NameRequired), resourceCulture);
        public static string Branch_Err_NoBusinessDetailed => ResourceManager.GetString(nameof(Branch_Err_NoBusinessDetailed), resourceCulture);
        public static string Branch_Err_NotFound => ResourceManager.GetString(nameof(Branch_Err_NotFound), resourceCulture);
        public static string Branch_Lbl_AccentColor => ResourceManager.GetString(nameof(Branch_Lbl_AccentColor), resourceCulture);
        public static string Branch_Lbl_Description => ResourceManager.GetString(nameof(Branch_Lbl_Description), resourceCulture);
        public static string Branch_Lbl_LetterShort => ResourceManager.GetString(nameof(Branch_Lbl_LetterShort), resourceCulture);
        public static string Branch_Lbl_NameRequiredModal => ResourceManager.GetString(nameof(Branch_Lbl_NameRequiredModal), resourceCulture);
        public static string Branch_ModalBtn_CancelModal => ResourceManager.GetString(nameof(Branch_ModalBtn_CancelModal), resourceCulture);
        public static string Branch_ModalTitle_Create => ResourceManager.GetString(nameof(Branch_ModalTitle_Create), resourceCulture);
        public static string Branch_ModalTitle_Edit => ResourceManager.GetString(nameof(Branch_ModalTitle_Edit), resourceCulture);
        public static string Branch_Msg_Created => ResourceManager.GetString(nameof(Branch_Msg_Created), resourceCulture);
        public static string Branch_Msg_Deleted => ResourceManager.GetString(nameof(Branch_Msg_Deleted), resourceCulture);
        public static string Branch_Msg_NoBusinessBlock => ResourceManager.GetString(nameof(Branch_Msg_NoBusinessBlock), resourceCulture);
        public static string Branch_Msg_SaveToManageBranches => ResourceManager.GetString(nameof(Branch_Msg_SaveToManageBranches), resourceCulture);
        public static string Branch_Msg_Updated => ResourceManager.GetString(nameof(Branch_Msg_Updated), resourceCulture);
        public static string Branch_NoRows => ResourceManager.GetString(nameof(Branch_NoRows), resourceCulture);
        public static string Branch_Page_DetailsTitle => ResourceManager.GetString(nameof(Branch_Page_DetailsTitle), resourceCulture);
        public static string Branch_Page_EditTitle => ResourceManager.GetString(nameof(Branch_Page_EditTitle), resourceCulture);
        public static string Branch_RowTooltip_Delete => ResourceManager.GetString(nameof(Branch_RowTooltip_Delete), resourceCulture);
        public static string Branch_RowTooltip_Edit => ResourceManager.GetString(nameof(Branch_RowTooltip_Edit), resourceCulture);
        public static string Branch_ToastMessage_Saved => ResourceManager.GetString(nameof(Branch_ToastMessage_Saved), resourceCulture);
        public static string Branch_ToastTitle_Saved => ResourceManager.GetString(nameof(Branch_ToastTitle_Saved), resourceCulture);
        public static string Branch_Val_AttcolorHex => ResourceManager.GetString(nameof(Branch_Val_AttcolorHex), resourceCulture);
        public static string Btn_SaveChanges => ResourceManager.GetString(nameof(Btn_SaveChanges), resourceCulture);
        public static string Common_Home => ResourceManager.GetString(nameof(Common_Home), resourceCulture);
        public static string Common_Intranet => ResourceManager.GetString(nameof(Common_Intranet), resourceCulture);
        public static string JsBranch_CreateFail => ResourceManager.GetString(nameof(JsBranch_CreateFail), resourceCulture);
        public static string JsBranch_DeleteConfirm => ResourceManager.GetString(nameof(JsBranch_DeleteConfirm), resourceCulture);
        public static string JsBranch_DeleteFail => ResourceManager.GetString(nameof(JsBranch_DeleteFail), resourceCulture);
        public static string JsBranch_NetworkError => ResourceManager.GetString(nameof(JsBranch_NetworkError), resourceCulture);
        public static string JsBranch_NewNeedsBusiness => ResourceManager.GetString(nameof(JsBranch_NewNeedsBusiness), resourceCulture);
        public static string JsBranch_NoBusinessInline => ResourceManager.GetString(nameof(JsBranch_NoBusinessInline), resourceCulture);
        public static string JsBranch_RefreshFail => ResourceManager.GetString(nameof(JsBranch_RefreshFail), resourceCulture);
        public static string JsBranch_SaveFail => ResourceManager.GetString(nameof(JsBranch_SaveFail), resourceCulture);
        public static string JsBranch_UseInlineFirst => ResourceManager.GetString(nameof(JsBranch_UseInlineFirst), resourceCulture);
    }
}
