//------------------------------------------------------------------------------
// Auto-generated by _gen_clientv2_resources.js — ClientV2 UI strings (87
// entries).
//------------------------------------------------------------------------------
namespace Desing.Resources
{
    using System;
    using global::System.Globalization;
    using global::System.Resources;

    /// <summary>TSql_Client_V2 module: localized strings (.resx); UICulture desde LanguageUiHelper.</summary>
    public class ClientV2
    {
        private static ResourceManager resourceMan;
        private static CultureInfo resourceCulture;

        public static ResourceManager ResourceManager =>
            resourceMan ??
            (resourceMan = new global::Desing.Helpers.DbBackedResourceManager(
                "Desing.Resources.ClientV2", typeof(ClientV2).Assembly, "ClientV2"));

        public static CultureInfo Culture
        {
            get => resourceCulture;
            set => resourceCulture = value;
        }
        public static string Btn_Cancel => ResourceManager.GetString(nameof(Btn_Cancel), resourceCulture);
        public static string Btn_Delete => ResourceManager.GetString(nameof(Btn_Delete), resourceCulture);
        public static string Btn_Edit => ResourceManager.GetString(nameof(Btn_Edit), resourceCulture);
        public static string Btn_Exit => ResourceManager.GetString(nameof(Btn_Exit), resourceCulture);
        public static string Btn_New => ResourceManager.GetString(nameof(Btn_New), resourceCulture);
        public static string Btn_Save => ResourceManager.GetString(nameof(Btn_Save), resourceCulture);
        public static string Btn_SaveChanges => ResourceManager.GetString(nameof(Btn_SaveChanges), resourceCulture);
        public static string Col_Code => ResourceManager.GetString(nameof(Col_Code), resourceCulture);
        public static string Col_Email => ResourceManager.GetString(nameof(Col_Email), resourceCulture);
        public static string Col_Logo => ResourceManager.GetString(nameof(Col_Logo), resourceCulture);
        public static string Col_Name => ResourceManager.GetString(nameof(Col_Name), resourceCulture);
        public static string Col_Phone => ResourceManager.GetString(nameof(Col_Phone), resourceCulture);
        public static string Col_State => ResourceManager.GetString(nameof(Col_State), resourceCulture);
        public static string Col_TaxId => ResourceManager.GetString(nameof(Col_TaxId), resourceCulture);
        public static string Common_Home => ResourceManager.GetString(nameof(Common_Home), resourceCulture);
        public static string Common_Intranet => ResourceManager.GetString(nameof(Common_Intranet), resourceCulture);
        public static string Details_Field_Active => ResourceManager.GetString(nameof(Details_Field_Active), resourceCulture);
        public static string Details_Field_AddressFormatted => ResourceManager.GetString(nameof(Details_Field_AddressFormatted), resourceCulture);
        public static string Details_Field_Code => ResourceManager.GetString(nameof(Details_Field_Code), resourceCulture);
        public static string Details_Field_Email => ResourceManager.GetString(nameof(Details_Field_Email), resourceCulture);
        public static string Details_Field_Icon => ResourceManager.GetString(nameof(Details_Field_Icon), resourceCulture);
        public static string Details_Field_Logo => ResourceManager.GetString(nameof(Details_Field_Logo), resourceCulture);
        public static string Details_Field_MethodOfPayment => ResourceManager.GetString(nameof(Details_Field_MethodOfPayment), resourceCulture);
        public static string Details_Field_Name => ResourceManager.GetString(nameof(Details_Field_Name), resourceCulture);
        public static string Details_Field_Phone => ResourceManager.GetString(nameof(Details_Field_Phone), resourceCulture);
        public static string Details_Field_TaxId => ResourceManager.GetString(nameof(Details_Field_TaxId), resourceCulture);
        public static string Details_MapTitle => ResourceManager.GetString(nameof(Details_MapTitle), resourceCulture);
        public static string Details_NoBoolValue => ResourceManager.GetString(nameof(Details_NoBoolValue), resourceCulture);
        public static string Details_NoValue => ResourceManager.GetString(nameof(Details_NoValue), resourceCulture);
        public static string Details_Section_AddressDetail => ResourceManager.GetString(nameof(Details_Section_AddressDetail), resourceCulture);
        public static string Details_YesValue => ResourceManager.GetString(nameof(Details_YesValue), resourceCulture);
        public static string Dt_MenuAria => ResourceManager.GetString(nameof(Dt_MenuAria), resourceCulture);
        public static string Dt_Rows_All => ResourceManager.GetString(nameof(Dt_Rows_All), resourceCulture);
        public static string Dt_Rows_N => ResourceManager.GetString(nameof(Dt_Rows_N), resourceCulture);
        public static string Dt_Section_ColumnsVisible => ResourceManager.GetString(nameof(Dt_Section_ColumnsVisible), resourceCulture);
        public static string Dt_Section_Export => ResourceManager.GetString(nameof(Dt_Section_Export), resourceCulture);
        public static string Dt_Section_Records => ResourceManager.GetString(nameof(Dt_Section_Records), resourceCulture);
        public static string Err_CannotDeleteHasDocuments => ResourceManager.GetString(nameof(Err_CannotDeleteHasDocuments), resourceCulture);
        public static string Err_CannotDeleteHasJobsides => ResourceManager.GetString(nameof(Err_CannotDeleteHasJobsides), resourceCulture);
        public static string Err_CannotDeleteHasOffers => ResourceManager.GetString(nameof(Err_CannotDeleteHasOffers), resourceCulture);
        public static string Err_ClientNotFound => ResourceManager.GetString(nameof(Err_ClientNotFound), resourceCulture);
        public static string Err_IconFormatNotAllowed => ResourceManager.GetString(nameof(Err_IconFormatNotAllowed), resourceCulture);
        public static string Err_IconSaveFailed => ResourceManager.GetString(nameof(Err_IconSaveFailed), resourceCulture);
        public static string Err_LogoFormatNotAllowed => ResourceManager.GetString(nameof(Err_LogoFormatNotAllowed), resourceCulture);
        public static string Err_LogoSaveFailed => ResourceManager.GetString(nameof(Err_LogoSaveFailed), resourceCulture);
        public static string Google_NotConfiguredBody => ResourceManager.GetString(nameof(Google_NotConfiguredBody), resourceCulture);
        public static string Google_NotConfiguredStrong => ResourceManager.GetString(nameof(Google_NotConfiguredStrong), resourceCulture);
        public static string Index_Breadcrumb => ResourceManager.GetString(nameof(Index_Breadcrumb), resourceCulture);
        public static string Index_CreateClient => ResourceManager.GetString(nameof(Index_CreateClient), resourceCulture);
        public static string Js_ConfirmDeleteClient => ResourceManager.GetString(nameof(Js_ConfirmDeleteClient), resourceCulture);
        public static string Lbl_Active => ResourceManager.GetString(nameof(Lbl_Active), resourceCulture);
        public static string Lbl_ActiveCheckbox => ResourceManager.GetString(nameof(Lbl_ActiveCheckbox), resourceCulture);
        public static string Lbl_AddressGooglePlaces => ResourceManager.GetString(nameof(Lbl_AddressGooglePlaces), resourceCulture);
        public static string Lbl_Code => ResourceManager.GetString(nameof(Lbl_Code), resourceCulture);
        public static string Lbl_Email => ResourceManager.GetString(nameof(Lbl_Email), resourceCulture);
        public static string Lbl_Icon => ResourceManager.GetString(nameof(Lbl_Icon), resourceCulture);
        public static string Lbl_Logo => ResourceManager.GetString(nameof(Lbl_Logo), resourceCulture);
        public static string Lbl_MethodOfPayment => ResourceManager.GetString(nameof(Lbl_MethodOfPayment), resourceCulture);
        public static string Lbl_MethodOfPaymentEmpty => ResourceManager.GetString(nameof(Lbl_MethodOfPaymentEmpty), resourceCulture);
        public static string Lbl_NameRequired => ResourceManager.GetString(nameof(Lbl_NameRequired), resourceCulture);
        public static string Lbl_Phone => ResourceManager.GetString(nameof(Lbl_Phone), resourceCulture);
        public static string Lbl_TaxId => ResourceManager.GetString(nameof(Lbl_TaxId), resourceCulture);
        public static string List_LinkDeleteLockedDocumentsTooltip => ResourceManager.GetString(nameof(List_LinkDeleteLockedDocumentsTooltip), resourceCulture);
        public static string List_LinkDeleteLockedJobsidesTooltip => ResourceManager.GetString(nameof(List_LinkDeleteLockedJobsidesTooltip), resourceCulture);
        public static string List_LinkDeleteLockedOffersTooltip => ResourceManager.GetString(nameof(List_LinkDeleteLockedOffersTooltip), resourceCulture);
        public static string List_LinkDeleteTooltip => ResourceManager.GetString(nameof(List_LinkDeleteTooltip), resourceCulture);
        public static string List_LinkEditTooltip => ResourceManager.GetString(nameof(List_LinkEditTooltip), resourceCulture);
        public static string List_LinkOpenTooltip => ResourceManager.GetString(nameof(List_LinkOpenTooltip), resourceCulture);
        public static string Page_CreateTitle => ResourceManager.GetString(nameof(Page_CreateTitle), resourceCulture);
        public static string Page_EditTitle => ResourceManager.GetString(nameof(Page_EditTitle), resourceCulture);
        public static string Ph_Code => ResourceManager.GetString(nameof(Ph_Code), resourceCulture);
        public static string Ph_Email => ResourceManager.GetString(nameof(Ph_Email), resourceCulture);
        public static string Ph_Name => ResourceManager.GetString(nameof(Ph_Name), resourceCulture);
        public static string Ph_Phone => ResourceManager.GetString(nameof(Ph_Phone), resourceCulture);
        public static string Ph_TaxId => ResourceManager.GetString(nameof(Ph_TaxId), resourceCulture);
        public static string State_Active => ResourceManager.GetString(nameof(State_Active), resourceCulture);
        public static string State_Inactive => ResourceManager.GetString(nameof(State_Inactive), resourceCulture);
        public static string ToastMessage_ClientCreated => ResourceManager.GetString(nameof(ToastMessage_ClientCreated), resourceCulture);
        public static string ToastMessage_ClientDeleted => ResourceManager.GetString(nameof(ToastMessage_ClientDeleted), resourceCulture);
        public static string ToastMessage_ClientUpdated => ResourceManager.GetString(nameof(ToastMessage_ClientUpdated), resourceCulture);
        public static string ToastTitle_CreateClient => ResourceManager.GetString(nameof(ToastTitle_CreateClient), resourceCulture);
        public static string ToastTitle_DeleteClient => ResourceManager.GetString(nameof(ToastTitle_DeleteClient), resourceCulture);
        public static string ToastTitle_EditClient => ResourceManager.GetString(nameof(ToastTitle_EditClient), resourceCulture);
        public static string Val_DuplicateNameCreate => ResourceManager.GetString(nameof(Val_DuplicateNameCreate), resourceCulture);
        public static string Val_DuplicateNameEdit => ResourceManager.GetString(nameof(Val_DuplicateNameEdit), resourceCulture);
        public static string Val_EmailFormat => ResourceManager.GetString(nameof(Val_EmailFormat), resourceCulture);
        public static string Val_NameRequired => ResourceManager.GetString(nameof(Val_NameRequired), resourceCulture);
    }
}
