//------------------------------------------------------------------------------
// Auto-generated by _gen_common_resources.js — Common UI strings (115
// entries). Cubre layout, footer, navbar/sidebar/switcher, Error, Lockout,
// cuentas (Login/Register/Forgot/Reset), defaults DataTables y Google Places.
//------------------------------------------------------------------------------
namespace Desing.Resources
{
    using System;
    using global::System.Globalization;
    using global::System.Resources;

    /// <summary>Modulo Common: cadenas de UI globales (.resx + override BD vía DbBackedResourceManager).</summary>
    public class Common
    {
        private static ResourceManager resourceMan;
        private static CultureInfo resourceCulture;

        public static ResourceManager ResourceManager =>
            resourceMan ??
            (resourceMan = new global::Desing.Helpers.DbBackedResourceManager(
                "Desing.Resources.Common", typeof(Common).Assembly, "Common"));

        public static CultureInfo Culture
        {
            get => resourceCulture;
            set => resourceCulture = value;
        }
        public static string Account_EmailConfirmation_Subject => ResourceManager.GetString(nameof(Account_EmailConfirmation_Subject), resourceCulture);
        public static string Account_Err_EmailNotConfirmed => ResourceManager.GetString(nameof(Account_Err_EmailNotConfirmed), resourceCulture);
        public static string Account_Err_InvalidCode => ResourceManager.GetString(nameof(Account_Err_InvalidCode), resourceCulture);
        public static string Account_Err_LoginRequired => ResourceManager.GetString(nameof(Account_Err_LoginRequired), resourceCulture);
        public static string Account_Err_UserNotRegistered => ResourceManager.GetString(nameof(Account_Err_UserNotRegistered), resourceCulture);
        public static string Action_OpenList => ResourceManager.GetString(nameof(Action_OpenList), resourceCulture);
        public static string App_BrandFallback => ResourceManager.GetString(nameof(App_BrandFallback), resourceCulture);
        public static string App_EnvironmentLabel => ResourceManager.GetString(nameof(App_EnvironmentLabel), resourceCulture);
        public static string Aria_CloseModal => ResourceManager.GetString(nameof(Aria_CloseModal), resourceCulture);
        public static string Aria_LanguageSwitcher => ResourceManager.GetString(nameof(Aria_LanguageSwitcher), resourceCulture);
        public static string Aria_TogglePassword => ResourceManager.GetString(nameof(Aria_TogglePassword), resourceCulture);
        public static string Btn_Back => ResourceManager.GetString(nameof(Btn_Back), resourceCulture);
        public static string Btn_Cancel => ResourceManager.GetString(nameof(Btn_Cancel), resourceCulture);
        public static string Btn_Close => ResourceManager.GetString(nameof(Btn_Close), resourceCulture);
        public static string Btn_Confirm => ResourceManager.GetString(nameof(Btn_Confirm), resourceCulture);
        public static string Btn_Create => ResourceManager.GetString(nameof(Btn_Create), resourceCulture);
        public static string Btn_Delete => ResourceManager.GetString(nameof(Btn_Delete), resourceCulture);
        public static string Btn_Details => ResourceManager.GetString(nameof(Btn_Details), resourceCulture);
        public static string Btn_Edit => ResourceManager.GetString(nameof(Btn_Edit), resourceCulture);
        public static string Btn_Save => ResourceManager.GetString(nameof(Btn_Save), resourceCulture);
        public static string Btn_SaveChanges => ResourceManager.GetString(nameof(Btn_SaveChanges), resourceCulture);
        public static string Btn_Search => ResourceManager.GetString(nameof(Btn_Search), resourceCulture);
        public static string Btn_Send => ResourceManager.GetString(nameof(Btn_Send), resourceCulture);
        public static string ConfirmEmail_Lead => ResourceManager.GetString(nameof(ConfirmEmail_Lead), resourceCulture);
        public static string ConfirmEmail_Link => ResourceManager.GetString(nameof(ConfirmEmail_Link), resourceCulture);
        public static string ConfirmEmail_Title => ResourceManager.GetString(nameof(ConfirmEmail_Title), resourceCulture);
        public static string Display_Code => ResourceManager.GetString(nameof(Display_Code), resourceCulture);
        public static string Display_ConfirmPassword => ResourceManager.GetString(nameof(Display_ConfirmPassword), resourceCulture);
        public static string Display_Email => ResourceManager.GetString(nameof(Display_Email), resourceCulture);
        public static string Display_Password => ResourceManager.GetString(nameof(Display_Password), resourceCulture);
        public static string Display_RememberBrowser => ResourceManager.GetString(nameof(Display_RememberBrowser), resourceCulture);
        public static string Display_RememberMe => ResourceManager.GetString(nameof(Display_RememberMe), resourceCulture);
        public static string Display_UserName => ResourceManager.GetString(nameof(Display_UserName), resourceCulture);
        public static string Dt_Btn_ColVis => ResourceManager.GetString(nameof(Dt_Btn_ColVis), resourceCulture);
        public static string Dt_Btn_Copy => ResourceManager.GetString(nameof(Dt_Btn_Copy), resourceCulture);
        public static string Dt_Btn_Csv => ResourceManager.GetString(nameof(Dt_Btn_Csv), resourceCulture);
        public static string Dt_Btn_Excel => ResourceManager.GetString(nameof(Dt_Btn_Excel), resourceCulture);
        public static string Dt_Btn_PageLength => ResourceManager.GetString(nameof(Dt_Btn_PageLength), resourceCulture);
        public static string Dt_Btn_Pdf => ResourceManager.GetString(nameof(Dt_Btn_Pdf), resourceCulture);
        public static string Dt_Btn_Print => ResourceManager.GetString(nameof(Dt_Btn_Print), resourceCulture);
        public static string Dt_MenuAria => ResourceManager.GetString(nameof(Dt_MenuAria), resourceCulture);
        public static string Dt_Rows_All => ResourceManager.GetString(nameof(Dt_Rows_All), resourceCulture);
        public static string Dt_Rows_N => ResourceManager.GetString(nameof(Dt_Rows_N), resourceCulture);
        public static string Dt_Section_ColumnsVisible => ResourceManager.GetString(nameof(Dt_Section_ColumnsVisible), resourceCulture);
        public static string Dt_Section_Export => ResourceManager.GetString(nameof(Dt_Section_Export), resourceCulture);
        public static string Dt_Section_Records => ResourceManager.GetString(nameof(Dt_Section_Records), resourceCulture);
        public static string Error_Subtitle => ResourceManager.GetString(nameof(Error_Subtitle), resourceCulture);
        public static string Error_Title => ResourceManager.GetString(nameof(Error_Title), resourceCulture);
        public static string ExternalLogin_FailureSubtitle => ResourceManager.GetString(nameof(ExternalLogin_FailureSubtitle), resourceCulture);
        public static string ExternalLogin_FailureTitle => ResourceManager.GetString(nameof(ExternalLogin_FailureTitle), resourceCulture);
        public static string Footer_LastReleaseLabel => ResourceManager.GetString(nameof(Footer_LastReleaseLabel), resourceCulture);
        public static string Forgot_Btn_Send => ResourceManager.GetString(nameof(Forgot_Btn_Send), resourceCulture);
        public static string Forgot_ConfirmationMessage => ResourceManager.GetString(nameof(Forgot_ConfirmationMessage), resourceCulture);
        public static string Forgot_ConfirmationTitle => ResourceManager.GetString(nameof(Forgot_ConfirmationTitle), resourceCulture);
        public static string Forgot_Heading => ResourceManager.GetString(nameof(Forgot_Heading), resourceCulture);
        public static string Forgot_Lbl_Email => ResourceManager.GetString(nameof(Forgot_Lbl_Email), resourceCulture);
        public static string Forgot_Link_BackToLogin => ResourceManager.GetString(nameof(Forgot_Link_BackToLogin), resourceCulture);
        public static string Forgot_PageTitle => ResourceManager.GetString(nameof(Forgot_PageTitle), resourceCulture);
        public static string Forgot_Subtitle => ResourceManager.GetString(nameof(Forgot_Subtitle), resourceCulture);
        public static string Google_Aria_MapPreview => ResourceManager.GetString(nameof(Google_Aria_MapPreview), resourceCulture);
        public static string Google_Err_ApiLoadFailed => ResourceManager.GetString(nameof(Google_Err_ApiLoadFailed), resourceCulture);
        public static string Google_Lbl_AdminArea1 => ResourceManager.GetString(nameof(Google_Lbl_AdminArea1), resourceCulture);
        public static string Google_Lbl_CountryCode => ResourceManager.GetString(nameof(Google_Lbl_CountryCode), resourceCulture);
        public static string Google_Lbl_FormattedAddress => ResourceManager.GetString(nameof(Google_Lbl_FormattedAddress), resourceCulture);
        public static string Google_Lbl_Locality => ResourceManager.GetString(nameof(Google_Lbl_Locality), resourceCulture);
        public static string Google_Lbl_Map => ResourceManager.GetString(nameof(Google_Lbl_Map), resourceCulture);
        public static string Google_Lbl_PostalCode => ResourceManager.GetString(nameof(Google_Lbl_PostalCode), resourceCulture);
        public static string Google_Lbl_Route => ResourceManager.GetString(nameof(Google_Lbl_Route), resourceCulture);
        public static string Google_Lbl_Search => ResourceManager.GetString(nameof(Google_Lbl_Search), resourceCulture);
        public static string Google_Lbl_StreetNumber => ResourceManager.GetString(nameof(Google_Lbl_StreetNumber), resourceCulture);
        public static string Google_Lbl_Subpremise => ResourceManager.GetString(nameof(Google_Lbl_Subpremise), resourceCulture);
        public static string Google_Msg_NoAddress => ResourceManager.GetString(nameof(Google_Msg_NoAddress), resourceCulture);
        public static string Google_Ph_Search => ResourceManager.GetString(nameof(Google_Ph_Search), resourceCulture);
        public static string Google_Title => ResourceManager.GetString(nameof(Google_Title), resourceCulture);
        public static string Home_PageHeading => ResourceManager.GetString(nameof(Home_PageHeading), resourceCulture);
        public static string LanguageSwitcher_LockedBadge => ResourceManager.GetString(nameof(LanguageSwitcher_LockedBadge), resourceCulture);
        public static string LanguageSwitcher_LockedSuffix => ResourceManager.GetString(nameof(LanguageSwitcher_LockedSuffix), resourceCulture);
        public static string Lockout_PageTitle => ResourceManager.GetString(nameof(Lockout_PageTitle), resourceCulture);
        public static string Lockout_Subtitle => ResourceManager.GetString(nameof(Lockout_Subtitle), resourceCulture);
        public static string Lockout_Title => ResourceManager.GetString(nameof(Lockout_Title), resourceCulture);
        public static string Login_Btn_SignIn => ResourceManager.GetString(nameof(Login_Btn_SignIn), resourceCulture);
        public static string Login_Lbl_Email => ResourceManager.GetString(nameof(Login_Lbl_Email), resourceCulture);
        public static string Login_Lbl_Password => ResourceManager.GetString(nameof(Login_Lbl_Password), resourceCulture);
        public static string Login_Lbl_RememberMe => ResourceManager.GetString(nameof(Login_Lbl_RememberMe), resourceCulture);
        public static string Login_Link_ForgotPassword => ResourceManager.GetString(nameof(Login_Link_ForgotPassword), resourceCulture);
        public static string Login_PageTitle => ResourceManager.GetString(nameof(Login_PageTitle), resourceCulture);
        public static string Login_Subtitle => ResourceManager.GetString(nameof(Login_Subtitle), resourceCulture);
        public static string Login_Welcome => ResourceManager.GetString(nameof(Login_Welcome), resourceCulture);
        public static string Register_BreadcrumbEmployees => ResourceManager.GetString(nameof(Register_BreadcrumbEmployees), resourceCulture);
        public static string Register_BreadcrumbHome => ResourceManager.GetString(nameof(Register_BreadcrumbHome), resourceCulture);
        public static string Register_Btn_Cancel => ResourceManager.GetString(nameof(Register_Btn_Cancel), resourceCulture);
        public static string Register_Btn_Create => ResourceManager.GetString(nameof(Register_Btn_Create), resourceCulture);
        public static string Register_CardTitle => ResourceManager.GetString(nameof(Register_CardTitle), resourceCulture);
        public static string Register_Lbl_ConfirmPassword => ResourceManager.GetString(nameof(Register_Lbl_ConfirmPassword), resourceCulture);
        public static string Register_Lbl_Email => ResourceManager.GetString(nameof(Register_Lbl_Email), resourceCulture);
        public static string Register_Lbl_Password => ResourceManager.GetString(nameof(Register_Lbl_Password), resourceCulture);
        public static string Register_PageHeading => ResourceManager.GetString(nameof(Register_PageHeading), resourceCulture);
        public static string Register_PageTitle => ResourceManager.GetString(nameof(Register_PageTitle), resourceCulture);
        public static string Reset_Btn_Submit => ResourceManager.GetString(nameof(Reset_Btn_Submit), resourceCulture);
        public static string Reset_ConfirmationLead => ResourceManager.GetString(nameof(Reset_ConfirmationLead), resourceCulture);
        public static string Reset_ConfirmationLink => ResourceManager.GetString(nameof(Reset_ConfirmationLink), resourceCulture);
        public static string Reset_ConfirmationTitle => ResourceManager.GetString(nameof(Reset_ConfirmationTitle), resourceCulture);
        public static string Reset_Heading => ResourceManager.GetString(nameof(Reset_Heading), resourceCulture);
        public static string Reset_Lbl_ConfirmPassword => ResourceManager.GetString(nameof(Reset_Lbl_ConfirmPassword), resourceCulture);
        public static string Reset_Lbl_Email => ResourceManager.GetString(nameof(Reset_Lbl_Email), resourceCulture);
        public static string Reset_Lbl_NewPassword => ResourceManager.GetString(nameof(Reset_Lbl_NewPassword), resourceCulture);
        public static string Reset_Link_BackToLogin => ResourceManager.GetString(nameof(Reset_Link_BackToLogin), resourceCulture);
        public static string Reset_PageTitle => ResourceManager.GetString(nameof(Reset_PageTitle), resourceCulture);
        public static string Reset_Subtitle => ResourceManager.GetString(nameof(Reset_Subtitle), resourceCulture);
        public static string Val_CodeRequired => ResourceManager.GetString(nameof(Val_CodeRequired), resourceCulture);
        public static string Val_EmailInvalid => ResourceManager.GetString(nameof(Val_EmailInvalid), resourceCulture);
        public static string Val_EmailRequired => ResourceManager.GetString(nameof(Val_EmailRequired), resourceCulture);
        public static string Val_PasswordRequired => ResourceManager.GetString(nameof(Val_PasswordRequired), resourceCulture);
        public static string Val_PasswordTooShort => ResourceManager.GetString(nameof(Val_PasswordTooShort), resourceCulture);
        public static string Val_PasswordsDoNotMatch => ResourceManager.GetString(nameof(Val_PasswordsDoNotMatch), resourceCulture);
    }
}
