//------------------------------------------------------------------------------
// Auto-generated by _gen_company_resources.js — Empresa UI strings (76
// entries).
//------------------------------------------------------------------------------
namespace Desing.Resources
{
    using System;
    using global::System.Globalization;
    using global::System.Resources;

    /// <summary>TSql_Company module: localized strings (.resx); UICulture desde LanguageUiHelper.</summary>
    public class Company
    {
        private static ResourceManager resourceMan;
        private static CultureInfo resourceCulture;

        public static ResourceManager ResourceManager =>
            resourceMan ??
            (resourceMan = new global::Desing.Helpers.DbBackedResourceManager(
                "Desing.Resources.Company", typeof(Company).Assembly, "Company"));

        public static CultureInfo Culture
        {
            get => resourceCulture;
            set => resourceCulture = value;
        }
        public static string Btn_Cancel => ResourceManager.GetString(nameof(Btn_Cancel), resourceCulture);
        public static string Btn_Edit => ResourceManager.GetString(nameof(Btn_Edit), resourceCulture);
        public static string Btn_SaveChanges => ResourceManager.GetString(nameof(Btn_SaveChanges), resourceCulture);
        public static string Btn_SaveCompany => ResourceManager.GetString(nameof(Btn_SaveCompany), resourceCulture);
        public static string Col_AddLeter => ResourceManager.GetString(nameof(Col_AddLeter), resourceCulture);
        public static string Col_Address => ResourceManager.GetString(nameof(Col_Address), resourceCulture);
        public static string Col_Address2 => ResourceManager.GetString(nameof(Col_Address2), resourceCulture);
        public static string Col_City => ResourceManager.GetString(nameof(Col_City), resourceCulture);
        public static string Col_Country => ResourceManager.GetString(nameof(Col_Country), resourceCulture);
        public static string Col_Description => ResourceManager.GetString(nameof(Col_Description), resourceCulture);
        public static string Col_Logo => ResourceManager.GetString(nameof(Col_Logo), resourceCulture);
        public static string Col_Name => ResourceManager.GetString(nameof(Col_Name), resourceCulture);
        public static string Col_PostalCode => ResourceManager.GetString(nameof(Col_PostalCode), resourceCulture);
        public static string Col_State => ResourceManager.GetString(nameof(Col_State), resourceCulture);
        public static string Common_Home => ResourceManager.GetString(nameof(Common_Home), resourceCulture);
        public static string Dd_SelectPlaceholder => ResourceManager.GetString(nameof(Dd_SelectPlaceholder), resourceCulture);
        public static string Details_Field_AddLeter => ResourceManager.GetString(nameof(Details_Field_AddLeter), resourceCulture);
        public static string Details_Field_Address => ResourceManager.GetString(nameof(Details_Field_Address), resourceCulture);
        public static string Details_Field_Address2 => ResourceManager.GetString(nameof(Details_Field_Address2), resourceCulture);
        public static string Details_Field_City => ResourceManager.GetString(nameof(Details_Field_City), resourceCulture);
        public static string Details_Field_Country => ResourceManager.GetString(nameof(Details_Field_Country), resourceCulture);
        public static string Details_Field_Description => ResourceManager.GetString(nameof(Details_Field_Description), resourceCulture);
        public static string Details_Field_Name => ResourceManager.GetString(nameof(Details_Field_Name), resourceCulture);
        public static string Details_Field_Postal => ResourceManager.GetString(nameof(Details_Field_Postal), resourceCulture);
        public static string Details_Field_WorkLanguage => ResourceManager.GetString(nameof(Details_Field_WorkLanguage), resourceCulture);
        public static string Details_NoValue => ResourceManager.GetString(nameof(Details_NoValue), resourceCulture);
        public static string Details_WorkLanguageHint => ResourceManager.GetString(nameof(Details_WorkLanguageHint), resourceCulture);
        public static string Dt_MenuAria => ResourceManager.GetString(nameof(Dt_MenuAria), resourceCulture);
        public static string Dt_Rows_All => ResourceManager.GetString(nameof(Dt_Rows_All), resourceCulture);
        public static string Dt_Rows_N => ResourceManager.GetString(nameof(Dt_Rows_N), resourceCulture);
        public static string Dt_Section_ColumnsVisible => ResourceManager.GetString(nameof(Dt_Section_ColumnsVisible), resourceCulture);
        public static string Dt_Section_Export => ResourceManager.GetString(nameof(Dt_Section_Export), resourceCulture);
        public static string Dt_Section_Records => ResourceManager.GetString(nameof(Dt_Section_Records), resourceCulture);
        public static string Err_CannotDeleteRelated => ResourceManager.GetString(nameof(Err_CannotDeleteRelated), resourceCulture);
        public static string Err_CompanyNotFound => ResourceManager.GetString(nameof(Err_CompanyNotFound), resourceCulture);
        public static string Google_NotConfiguredBody => ResourceManager.GetString(nameof(Google_NotConfiguredBody), resourceCulture);
        public static string Google_NotConfiguredStrong => ResourceManager.GetString(nameof(Google_NotConfiguredStrong), resourceCulture);
        public static string Help_VisualTemplateEmployees => ResourceManager.GetString(nameof(Help_VisualTemplateEmployees), resourceCulture);
        public static string Index_Breadcrumb => ResourceManager.GetString(nameof(Index_Breadcrumb), resourceCulture);
        public static string Index_CreateCompany => ResourceManager.GetString(nameof(Index_CreateCompany), resourceCulture);
        public static string Js_ConfirmDeleteCompany => ResourceManager.GetString(nameof(Js_ConfirmDeleteCompany), resourceCulture);
        public static string Js_ConfirmToggleCompany => ResourceManager.GetString(nameof(Js_ConfirmToggleCompany), resourceCulture);
        public static string LanguageSelect_FlagHint => ResourceManager.GetString(nameof(LanguageSelect_FlagHint), resourceCulture);
        public static string Lbl_AddLeter => ResourceManager.GetString(nameof(Lbl_AddLeter), resourceCulture);
        public static string Lbl_AddressGooglePlaces => ResourceManager.GetString(nameof(Lbl_AddressGooglePlaces), resourceCulture);
        public static string Lbl_AddressLegacy => ResourceManager.GetString(nameof(Lbl_AddressLegacy), resourceCulture);
        public static string Lbl_AddressLegacy2 => ResourceManager.GetString(nameof(Lbl_AddressLegacy2), resourceCulture);
        public static string Lbl_CityLegacy => ResourceManager.GetString(nameof(Lbl_CityLegacy), resourceCulture);
        public static string Lbl_Country => ResourceManager.GetString(nameof(Lbl_Country), resourceCulture);
        public static string Lbl_Description => ResourceManager.GetString(nameof(Lbl_Description), resourceCulture);
        public static string Lbl_LegacyBlockHint => ResourceManager.GetString(nameof(Lbl_LegacyBlockHint), resourceCulture);
        public static string Lbl_LogoPath => ResourceManager.GetString(nameof(Lbl_LogoPath), resourceCulture);
        public static string Lbl_NameRequired => ResourceManager.GetString(nameof(Lbl_NameRequired), resourceCulture);
        public static string Lbl_PostalLegacy => ResourceManager.GetString(nameof(Lbl_PostalLegacy), resourceCulture);
        public static string Lbl_VisualTemplate => ResourceManager.GetString(nameof(Lbl_VisualTemplate), resourceCulture);
        public static string Lbl_WorkUiLanguageRequired => ResourceManager.GetString(nameof(Lbl_WorkUiLanguageRequired), resourceCulture);
        public static string List_LinkDeleteTooltip => ResourceManager.GetString(nameof(List_LinkDeleteTooltip), resourceCulture);
        public static string List_LinkEditTooltip => ResourceManager.GetString(nameof(List_LinkEditTooltip), resourceCulture);
        public static string List_LinkOpenTooltip => ResourceManager.GetString(nameof(List_LinkOpenTooltip), resourceCulture);
        public static string List_LinkToggleTooltip => ResourceManager.GetString(nameof(List_LinkToggleTooltip), resourceCulture);
        public static string Msg_CompanyDeleted => ResourceManager.GetString(nameof(Msg_CompanyDeleted), resourceCulture);
        public static string Msg_CompanyPaused => ResourceManager.GetString(nameof(Msg_CompanyPaused), resourceCulture);
        public static string Msg_CompanyResumed => ResourceManager.GetString(nameof(Msg_CompanyResumed), resourceCulture);
        public static string Page_CreateTitle => ResourceManager.GetString(nameof(Page_CreateTitle), resourceCulture);
        public static string Page_EditTitle => ResourceManager.GetString(nameof(Page_EditTitle), resourceCulture);
        public static string Plantilla_InheritGlobalDefault => ResourceManager.GetString(nameof(Plantilla_InheritGlobalDefault), resourceCulture);
        public static string State_Active => ResourceManager.GetString(nameof(State_Active), resourceCulture);
        public static string State_Inactive => ResourceManager.GetString(nameof(State_Inactive), resourceCulture);
        public static string ToastMessage_CompanySaved => ResourceManager.GetString(nameof(ToastMessage_CompanySaved), resourceCulture);
        public static string ToastMessage_CompanyUpdated => ResourceManager.GetString(nameof(ToastMessage_CompanyUpdated), resourceCulture);
        public static string ToastTitle_CreateCompany => ResourceManager.GetString(nameof(ToastTitle_CreateCompany), resourceCulture);
        public static string ToastTitle_EditCompany => ResourceManager.GetString(nameof(ToastTitle_EditCompany), resourceCulture);
        public static string Val_CompanyNameRequired => ResourceManager.GetString(nameof(Val_CompanyNameRequired), resourceCulture);
        public static string Val_DuplicateNameCreate => ResourceManager.GetString(nameof(Val_DuplicateNameCreate), resourceCulture);
        public static string Val_DuplicateNameEdit => ResourceManager.GetString(nameof(Val_DuplicateNameEdit), resourceCulture);
        public static string Val_UiLanguageRequired => ResourceManager.GetString(nameof(Val_UiLanguageRequired), resourceCulture);
    }
}
