//------------------------------------------------------------------------------
// Auto-generated by _gen_country_catalog_resources.js — Country (TSql_Countrys) UI strings (61
// entries).
//------------------------------------------------------------------------------
namespace Desing.Resources
{
    using System;
    using global::System.Globalization;
    using global::System.Resources;

    /// <summary>TSql_Countrys catalog: localized strings (.resx); UICulture desde LanguageUiHelper.</summary>
    public class Country
    {
        private static ResourceManager resourceMan;
        private static CultureInfo resourceCulture;

        public static ResourceManager ResourceManager =>
            resourceMan ??
            (resourceMan = new global::Desing.Helpers.DbBackedResourceManager(
                "Desing.Resources.Country", typeof(Country).Assembly, "Country"));

        public static CultureInfo Culture
        {
            get => resourceCulture;
            set => resourceCulture = value;
        }
        public static string Btn_New => ResourceManager.GetString(nameof(Btn_New), resourceCulture);
        public static string Col_Flag => ResourceManager.GetString(nameof(Col_Flag), resourceCulture);
        public static string Col_Iso2 => ResourceManager.GetString(nameof(Col_Iso2), resourceCulture);
        public static string Col_Iso3 => ResourceManager.GetString(nameof(Col_Iso3), resourceCulture);
        public static string Col_IsoNumber => ResourceManager.GetString(nameof(Col_IsoNumber), resourceCulture);
        public static string Col_Name => ResourceManager.GetString(nameof(Col_Name), resourceCulture);
        public static string Col_State => ResourceManager.GetString(nameof(Col_State), resourceCulture);
        public static string Common_Home => ResourceManager.GetString(nameof(Common_Home), resourceCulture);
        public static string Common_Settings => ResourceManager.GetString(nameof(Common_Settings), resourceCulture);
        public static string Details_Field_Active => ResourceManager.GetString(nameof(Details_Field_Active), resourceCulture);
        public static string Details_Field_Flag => ResourceManager.GetString(nameof(Details_Field_Flag), resourceCulture);
        public static string Details_Field_Iso2 => ResourceManager.GetString(nameof(Details_Field_Iso2), resourceCulture);
        public static string Details_Field_Iso3 => ResourceManager.GetString(nameof(Details_Field_Iso3), resourceCulture);
        public static string Details_Field_Name => ResourceManager.GetString(nameof(Details_Field_Name), resourceCulture);
        public static string Details_Field_NumberIso => ResourceManager.GetString(nameof(Details_Field_NumberIso), resourceCulture);
        public static string Details_NoBoolValue => ResourceManager.GetString(nameof(Details_NoBoolValue), resourceCulture);
        public static string Details_NoValue => ResourceManager.GetString(nameof(Details_NoValue), resourceCulture);
        public static string Details_YesValue => ResourceManager.GetString(nameof(Details_YesValue), resourceCulture);
        public static string Err_CannotDeleteHasCompanies => ResourceManager.GetString(nameof(Err_CannotDeleteHasCompanies), resourceCulture);
        public static string Err_CannotDeleteHasLanguages => ResourceManager.GetString(nameof(Err_CannotDeleteHasLanguages), resourceCulture);
        public static string Err_CountryNotFound => ResourceManager.GetString(nameof(Err_CountryNotFound), resourceCulture);
        public static string Index_Breadcrumb => ResourceManager.GetString(nameof(Index_Breadcrumb), resourceCulture);
        public static string Index_CreateCountry => ResourceManager.GetString(nameof(Index_CreateCountry), resourceCulture);
        public static string Js_ConfirmDeleteCountry => ResourceManager.GetString(nameof(Js_ConfirmDeleteCountry), resourceCulture);
        public static string Lbl_Active => ResourceManager.GetString(nameof(Lbl_Active), resourceCulture);
        public static string Lbl_ActiveCheckbox => ResourceManager.GetString(nameof(Lbl_ActiveCheckbox), resourceCulture);
        public static string Lbl_FlagPath => ResourceManager.GetString(nameof(Lbl_FlagPath), resourceCulture);
        public static string Lbl_Iso2 => ResourceManager.GetString(nameof(Lbl_Iso2), resourceCulture);
        public static string Lbl_Iso3 => ResourceManager.GetString(nameof(Lbl_Iso3), resourceCulture);
        public static string Lbl_NameRequired => ResourceManager.GetString(nameof(Lbl_NameRequired), resourceCulture);
        public static string Lbl_NumberIso => ResourceManager.GetString(nameof(Lbl_NumberIso), resourceCulture);
        public static string List_LinkDeleteLockedCompaniesTooltip => ResourceManager.GetString(nameof(List_LinkDeleteLockedCompaniesTooltip), resourceCulture);
        public static string List_LinkDeleteLockedLanguagesTooltip => ResourceManager.GetString(nameof(List_LinkDeleteLockedLanguagesTooltip), resourceCulture);
        public static string List_LinkDeleteTooltip => ResourceManager.GetString(nameof(List_LinkDeleteTooltip), resourceCulture);
        public static string List_LinkEditTooltip => ResourceManager.GetString(nameof(List_LinkEditTooltip), resourceCulture);
        public static string List_LinkOpenTooltip => ResourceManager.GetString(nameof(List_LinkOpenTooltip), resourceCulture);
        public static string List_NoFlag => ResourceManager.GetString(nameof(List_NoFlag), resourceCulture);
        public static string Page_CreateTitle => ResourceManager.GetString(nameof(Page_CreateTitle), resourceCulture);
        public static string Page_DetailsTitle => ResourceManager.GetString(nameof(Page_DetailsTitle), resourceCulture);
        public static string Page_EditTitle => ResourceManager.GetString(nameof(Page_EditTitle), resourceCulture);
        public static string Ph_FlagPath => ResourceManager.GetString(nameof(Ph_FlagPath), resourceCulture);
        public static string Ph_Iso2 => ResourceManager.GetString(nameof(Ph_Iso2), resourceCulture);
        public static string Ph_Iso3 => ResourceManager.GetString(nameof(Ph_Iso3), resourceCulture);
        public static string Ph_Name => ResourceManager.GetString(nameof(Ph_Name), resourceCulture);
        public static string Ph_NumberIso => ResourceManager.GetString(nameof(Ph_NumberIso), resourceCulture);
        public static string State_Active => ResourceManager.GetString(nameof(State_Active), resourceCulture);
        public static string State_Inactive => ResourceManager.GetString(nameof(State_Inactive), resourceCulture);
        public static string ToastMessage_CountryCreated => ResourceManager.GetString(nameof(ToastMessage_CountryCreated), resourceCulture);
        public static string ToastMessage_CountryDeleted => ResourceManager.GetString(nameof(ToastMessage_CountryDeleted), resourceCulture);
        public static string ToastMessage_CountryUpdated => ResourceManager.GetString(nameof(ToastMessage_CountryUpdated), resourceCulture);
        public static string ToastTitle_CreateCountry => ResourceManager.GetString(nameof(ToastTitle_CreateCountry), resourceCulture);
        public static string ToastTitle_DeleteCountry => ResourceManager.GetString(nameof(ToastTitle_DeleteCountry), resourceCulture);
        public static string ToastTitle_EditCountry => ResourceManager.GetString(nameof(ToastTitle_EditCountry), resourceCulture);
        public static string Val_DuplicateNameCreate => ResourceManager.GetString(nameof(Val_DuplicateNameCreate), resourceCulture);
        public static string Val_DuplicateNameEdit => ResourceManager.GetString(nameof(Val_DuplicateNameEdit), resourceCulture);
        public static string Val_FlagPathTooLong => ResourceManager.GetString(nameof(Val_FlagPathTooLong), resourceCulture);
        public static string Val_Iso2TooLong => ResourceManager.GetString(nameof(Val_Iso2TooLong), resourceCulture);
        public static string Val_Iso3TooLong => ResourceManager.GetString(nameof(Val_Iso3TooLong), resourceCulture);
        public static string Val_NameRequired => ResourceManager.GetString(nameof(Val_NameRequired), resourceCulture);
        public static string Val_NameTooLong => ResourceManager.GetString(nameof(Val_NameTooLong), resourceCulture);
        public static string Val_NumberIsoTooLong => ResourceManager.GetString(nameof(Val_NumberIsoTooLong), resourceCulture);
    }
}
