//------------------------------------------------------------------------------
// Auto-generated by _gen_documenttype_resources.js — DocumentType UI strings (52
// entries).
//------------------------------------------------------------------------------
namespace Desing.Resources
{
    using System;
    using global::System.Globalization;
    using global::System.Resources;

    /// <summary>TSql_DocumentType module: localized strings (.resx); UICulture desde LanguageUiHelper.</summary>
    public class DocumentType
    {
        private static ResourceManager resourceMan;
        private static CultureInfo resourceCulture;

        public static ResourceManager ResourceManager =>
            resourceMan ??
            (resourceMan = new global::Desing.Helpers.DbBackedResourceManager(
                "Desing.Resources.DocumentType", typeof(DocumentType).Assembly, "DocumentType"));

        public static CultureInfo Culture
        {
            get => resourceCulture;
            set => resourceCulture = value;
        }
        public static string Btn_New => ResourceManager.GetString(nameof(Btn_New), resourceCulture);
        public static string Col_Code => ResourceManager.GetString(nameof(Col_Code), resourceCulture);
        public static string Col_Description => ResourceManager.GetString(nameof(Col_Description), resourceCulture);
        public static string Col_Extensions => ResourceManager.GetString(nameof(Col_Extensions), resourceCulture);
        public static string Col_Name => ResourceManager.GetString(nameof(Col_Name), resourceCulture);
        public static string Col_State => ResourceManager.GetString(nameof(Col_State), resourceCulture);
        public static string Common_Home => ResourceManager.GetString(nameof(Common_Home), resourceCulture);
        public static string Common_Settings => ResourceManager.GetString(nameof(Common_Settings), resourceCulture);
        public static string Details_Field_Active => ResourceManager.GetString(nameof(Details_Field_Active), resourceCulture);
        public static string Details_Field_Code => ResourceManager.GetString(nameof(Details_Field_Code), resourceCulture);
        public static string Details_Field_Description => ResourceManager.GetString(nameof(Details_Field_Description), resourceCulture);
        public static string Details_Field_Extensions => ResourceManager.GetString(nameof(Details_Field_Extensions), resourceCulture);
        public static string Details_Field_Name => ResourceManager.GetString(nameof(Details_Field_Name), resourceCulture);
        public static string Details_NoBoolValue => ResourceManager.GetString(nameof(Details_NoBoolValue), resourceCulture);
        public static string Details_NoExtensionsAssigned => ResourceManager.GetString(nameof(Details_NoExtensionsAssigned), resourceCulture);
        public static string Details_NoValue => ResourceManager.GetString(nameof(Details_NoValue), resourceCulture);
        public static string Details_YesValue => ResourceManager.GetString(nameof(Details_YesValue), resourceCulture);
        public static string Err_CannotDeleteHasDocuments => ResourceManager.GetString(nameof(Err_CannotDeleteHasDocuments), resourceCulture);
        public static string Err_DocumentTypeNotFound => ResourceManager.GetString(nameof(Err_DocumentTypeNotFound), resourceCulture);
        public static string Ext_EmptyCatalog => ResourceManager.GetString(nameof(Ext_EmptyCatalog), resourceCulture);
        public static string Index_Breadcrumb => ResourceManager.GetString(nameof(Index_Breadcrumb), resourceCulture);
        public static string Index_CreateDocumentType => ResourceManager.GetString(nameof(Index_CreateDocumentType), resourceCulture);
        public static string Js_ConfirmDeleteDocumentType => ResourceManager.GetString(nameof(Js_ConfirmDeleteDocumentType), resourceCulture);
        public static string Lbl_Active => ResourceManager.GetString(nameof(Lbl_Active), resourceCulture);
        public static string Lbl_ActiveCheckbox => ResourceManager.GetString(nameof(Lbl_ActiveCheckbox), resourceCulture);
        public static string Lbl_Code => ResourceManager.GetString(nameof(Lbl_Code), resourceCulture);
        public static string Lbl_Description => ResourceManager.GetString(nameof(Lbl_Description), resourceCulture);
        public static string Lbl_Extensions => ResourceManager.GetString(nameof(Lbl_Extensions), resourceCulture);
        public static string Lbl_NameRequired => ResourceManager.GetString(nameof(Lbl_NameRequired), resourceCulture);
        public static string List_LinkDeleteLockedDocumentsTooltip => ResourceManager.GetString(nameof(List_LinkDeleteLockedDocumentsTooltip), resourceCulture);
        public static string List_LinkDeleteTooltip => ResourceManager.GetString(nameof(List_LinkDeleteTooltip), resourceCulture);
        public static string List_LinkEditTooltip => ResourceManager.GetString(nameof(List_LinkEditTooltip), resourceCulture);
        public static string List_LinkOpenTooltip => ResourceManager.GetString(nameof(List_LinkOpenTooltip), resourceCulture);
        public static string List_NoExtensions => ResourceManager.GetString(nameof(List_NoExtensions), resourceCulture);
        public static string Page_CreateTitle => ResourceManager.GetString(nameof(Page_CreateTitle), resourceCulture);
        public static string Page_DetailsTitle => ResourceManager.GetString(nameof(Page_DetailsTitle), resourceCulture);
        public static string Page_EditTitle => ResourceManager.GetString(nameof(Page_EditTitle), resourceCulture);
        public static string Ph_Code => ResourceManager.GetString(nameof(Ph_Code), resourceCulture);
        public static string Ph_Description => ResourceManager.GetString(nameof(Ph_Description), resourceCulture);
        public static string Ph_ExtensionFilter => ResourceManager.GetString(nameof(Ph_ExtensionFilter), resourceCulture);
        public static string Ph_Name => ResourceManager.GetString(nameof(Ph_Name), resourceCulture);
        public static string State_Active => ResourceManager.GetString(nameof(State_Active), resourceCulture);
        public static string State_Inactive => ResourceManager.GetString(nameof(State_Inactive), resourceCulture);
        public static string ToastMessage_DocumentTypeCreated => ResourceManager.GetString(nameof(ToastMessage_DocumentTypeCreated), resourceCulture);
        public static string ToastMessage_DocumentTypeDeleted => ResourceManager.GetString(nameof(ToastMessage_DocumentTypeDeleted), resourceCulture);
        public static string ToastMessage_DocumentTypeUpdated => ResourceManager.GetString(nameof(ToastMessage_DocumentTypeUpdated), resourceCulture);
        public static string ToastTitle_CreateDocumentType => ResourceManager.GetString(nameof(ToastTitle_CreateDocumentType), resourceCulture);
        public static string ToastTitle_DeleteDocumentType => ResourceManager.GetString(nameof(ToastTitle_DeleteDocumentType), resourceCulture);
        public static string ToastTitle_EditDocumentType => ResourceManager.GetString(nameof(ToastTitle_EditDocumentType), resourceCulture);
        public static string Val_DuplicateCodeCreate => ResourceManager.GetString(nameof(Val_DuplicateCodeCreate), resourceCulture);
        public static string Val_DuplicateCodeEdit => ResourceManager.GetString(nameof(Val_DuplicateCodeEdit), resourceCulture);
        public static string Val_NameRequired => ResourceManager.GetString(nameof(Val_NameRequired), resourceCulture);
    }
}
