//------------------------------------------------------------------------------
// Auto-generated by _gen_employee_resources.js — Empleado UI strings (104
// entries).
//------------------------------------------------------------------------------
namespace Desing.Resources
{
    using System;
    using global::System.Globalization;
    using global::System.Resources;

    /// <summary>TSql_Employee module: localized strings (.resx); UICulture desde LanguageUiHelper.</summary>
    public class Employee
    {
        private static ResourceManager resourceMan;
        private static CultureInfo resourceCulture;

        public static ResourceManager ResourceManager =>
            resourceMan ??
            (resourceMan = new global::Desing.Helpers.DbBackedResourceManager(
                "Desing.Resources.Employee", typeof(Employee).Assembly, "Employee"));

        public static CultureInfo Culture
        {
            get => resourceCulture;
            set => resourceCulture = value;
        }
        public static string Btn_Cancel => ResourceManager.GetString(nameof(Btn_Cancel), resourceCulture);
        public static string Btn_Delete => ResourceManager.GetString(nameof(Btn_Delete), resourceCulture);
        public static string Btn_Edit => ResourceManager.GetString(nameof(Btn_Edit), resourceCulture);
        public static string Btn_Exit => ResourceManager.GetString(nameof(Btn_Exit), resourceCulture);
        public static string Btn_SaveChanges => ResourceManager.GetString(nameof(Btn_SaveChanges), resourceCulture);
        public static string Btn_SaveEmployee => ResourceManager.GetString(nameof(Btn_SaveEmployee), resourceCulture);
        public static string Btn_SendMail => ResourceManager.GetString(nameof(Btn_SendMail), resourceCulture);
        public static string Btn_Toggle => ResourceManager.GetString(nameof(Btn_Toggle), resourceCulture);
        public static string Col_Account => ResourceManager.GetString(nameof(Col_Account), resourceCulture);
        public static string Col_Avatar => ResourceManager.GetString(nameof(Col_Avatar), resourceCulture);
        public static string Col_Company => ResourceManager.GetString(nameof(Col_Company), resourceCulture);
        public static string Col_CompanyLetter => ResourceManager.GetString(nameof(Col_CompanyLetter), resourceCulture);
        public static string Col_CreatedDate => ResourceManager.GetString(nameof(Col_CreatedDate), resourceCulture);
        public static string Col_Name => ResourceManager.GetString(nameof(Col_Name), resourceCulture);
        public static string Col_Password => ResourceManager.GetString(nameof(Col_Password), resourceCulture);
        public static string Col_State => ResourceManager.GetString(nameof(Col_State), resourceCulture);
        public static string Col_Surname => ResourceManager.GetString(nameof(Col_Surname), resourceCulture);
        public static string Col_TotalDesigns => ResourceManager.GetString(nameof(Col_TotalDesigns), resourceCulture);
        public static string Col_UserName => ResourceManager.GetString(nameof(Col_UserName), resourceCulture);
        public static string Common_Home => ResourceManager.GetString(nameof(Common_Home), resourceCulture);
        public static string Details_Field_Account => ResourceManager.GetString(nameof(Details_Field_Account), resourceCulture);
        public static string Details_Field_Company => ResourceManager.GetString(nameof(Details_Field_Company), resourceCulture);
        public static string Details_Field_CreatedDate => ResourceManager.GetString(nameof(Details_Field_CreatedDate), resourceCulture);
        public static string Details_Field_Name => ResourceManager.GetString(nameof(Details_Field_Name), resourceCulture);
        public static string Details_Field_Surname => ResourceManager.GetString(nameof(Details_Field_Surname), resourceCulture);
        public static string Details_Field_TotalDesigns => ResourceManager.GetString(nameof(Details_Field_TotalDesigns), resourceCulture);
        public static string Details_NoValue => ResourceManager.GetString(nameof(Details_NoValue), resourceCulture);
        public static string Dt_MenuAria => ResourceManager.GetString(nameof(Dt_MenuAria), resourceCulture);
        public static string Dt_Rows_All => ResourceManager.GetString(nameof(Dt_Rows_All), resourceCulture);
        public static string Dt_Rows_N => ResourceManager.GetString(nameof(Dt_Rows_N), resourceCulture);
        public static string Dt_Section_ColumnsVisible => ResourceManager.GetString(nameof(Dt_Section_ColumnsVisible), resourceCulture);
        public static string Dt_Section_Export => ResourceManager.GetString(nameof(Dt_Section_Export), resourceCulture);
        public static string Dt_Section_Records => ResourceManager.GetString(nameof(Dt_Section_Records), resourceCulture);
        public static string Err_CannotDeleteRelated => ResourceManager.GetString(nameof(Err_CannotDeleteRelated), resourceCulture);
        public static string Err_EmployeeNotFound => ResourceManager.GetString(nameof(Err_EmployeeNotFound), resourceCulture);
        public static string Err_GenericFailure => ResourceManager.GetString(nameof(Err_GenericFailure), resourceCulture);
        public static string Err_MailNotConfigured => ResourceManager.GetString(nameof(Err_MailNotConfigured), resourceCulture);
        public static string Err_UserNotFound => ResourceManager.GetString(nameof(Err_UserNotFound), resourceCulture);
        public static string Header_AccountInfo => ResourceManager.GetString(nameof(Header_AccountInfo), resourceCulture);
        public static string Index_Breadcrumb => ResourceManager.GetString(nameof(Index_Breadcrumb), resourceCulture);
        public static string Index_CreateEmployee => ResourceManager.GetString(nameof(Index_CreateEmployee), resourceCulture);
        public static string Js_ConfirmDeleteEmployee => ResourceManager.GetString(nameof(Js_ConfirmDeleteEmployee), resourceCulture);
        public static string Js_ConfirmSendMail => ResourceManager.GetString(nameof(Js_ConfirmSendMail), resourceCulture);
        public static string Js_ConfirmToggleEmployee => ResourceManager.GetString(nameof(Js_ConfirmToggleEmployee), resourceCulture);
        public static string Js_SendMailErrorFallback => ResourceManager.GetString(nameof(Js_SendMailErrorFallback), resourceCulture);
        public static string Js_SendMailNetworkError => ResourceManager.GetString(nameof(Js_SendMailNetworkError), resourceCulture);
        public static string Js_SendMailSuccessFallback => ResourceManager.GetString(nameof(Js_SendMailSuccessFallback), resourceCulture);
        public static string Js_SendMailUnexpected => ResourceManager.GetString(nameof(Js_SendMailUnexpected), resourceCulture);
        public static string Lbl_Company => ResourceManager.GetString(nameof(Lbl_Company), resourceCulture);
        public static string Lbl_CompanyHint => ResourceManager.GetString(nameof(Lbl_CompanyHint), resourceCulture);
        public static string Lbl_DeviceAllowed => ResourceManager.GetString(nameof(Lbl_DeviceAllowed), resourceCulture);
        public static string Lbl_DeviceId => ResourceManager.GetString(nameof(Lbl_DeviceId), resourceCulture);
        public static string Lbl_DeviceName => ResourceManager.GetString(nameof(Lbl_DeviceName), resourceCulture);
        public static string Lbl_DeviceSectionTitle => ResourceManager.GetString(nameof(Lbl_DeviceSectionTitle), resourceCulture);
        public static string Lbl_NameRequired => ResourceManager.GetString(nameof(Lbl_NameRequired), resourceCulture);
        public static string Lbl_Photo => ResourceManager.GetString(nameof(Lbl_Photo), resourceCulture);
        public static string Lbl_PhotoHint => ResourceManager.GetString(nameof(Lbl_PhotoHint), resourceCulture);
        public static string Lbl_SurnameRequired => ResourceManager.GetString(nameof(Lbl_SurnameRequired), resourceCulture);
        public static string List_LinkDeleteTooltip => ResourceManager.GetString(nameof(List_LinkDeleteTooltip), resourceCulture);
        public static string List_LinkEditTooltip => ResourceManager.GetString(nameof(List_LinkEditTooltip), resourceCulture);
        public static string List_LinkOpenTooltip => ResourceManager.GetString(nameof(List_LinkOpenTooltip), resourceCulture);
        public static string List_LinkSendMailTooltip => ResourceManager.GetString(nameof(List_LinkSendMailTooltip), resourceCulture);
        public static string List_LinkToggleTooltip => ResourceManager.GetString(nameof(List_LinkToggleTooltip), resourceCulture);
        public static string Modal_ActiveLegendActivated => ResourceManager.GetString(nameof(Modal_ActiveLegendActivated), resourceCulture);
        public static string Modal_ActiveLegendDeactivated => ResourceManager.GetString(nameof(Modal_ActiveLegendDeactivated), resourceCulture);
        public static string Modal_ActiveQuestionActivate => ResourceManager.GetString(nameof(Modal_ActiveQuestionActivate), resourceCulture);
        public static string Modal_ActiveQuestionDeactivate => ResourceManager.GetString(nameof(Modal_ActiveQuestionDeactivate), resourceCulture);
        public static string Modal_BtnActivate => ResourceManager.GetString(nameof(Modal_BtnActivate), resourceCulture);
        public static string Modal_BtnDeactivate => ResourceManager.GetString(nameof(Modal_BtnDeactivate), resourceCulture);
        public static string Modal_DeleteConfirm => ResourceManager.GetString(nameof(Modal_DeleteConfirm), resourceCulture);
        public static string Modal_DeleteLegend => ResourceManager.GetString(nameof(Modal_DeleteLegend), resourceCulture);
        public static string Msg_EmployeeActivated => ResourceManager.GetString(nameof(Msg_EmployeeActivated), resourceCulture);
        public static string Msg_EmployeeDeactivated => ResourceManager.GetString(nameof(Msg_EmployeeDeactivated), resourceCulture);
        public static string Msg_EmployeeDeleted => ResourceManager.GetString(nameof(Msg_EmployeeDeleted), resourceCulture);
        public static string Msg_MailSent => ResourceManager.GetString(nameof(Msg_MailSent), resourceCulture);
        public static string MySpace_Breadcrumb => ResourceManager.GetString(nameof(MySpace_Breadcrumb), resourceCulture);
        public static string MySpace_Field_FirstLogin => ResourceManager.GetString(nameof(MySpace_Field_FirstLogin), resourceCulture);
        public static string MySpace_Field_FullName => ResourceManager.GetString(nameof(MySpace_Field_FullName), resourceCulture);
        public static string MySpace_Field_TotalDesigns => ResourceManager.GetString(nameof(MySpace_Field_TotalDesigns), resourceCulture);
        public static string MySpace_Field_UserName => ResourceManager.GetString(nameof(MySpace_Field_UserName), resourceCulture);
        public static string MySpace_SectionTitle => ResourceManager.GetString(nameof(MySpace_SectionTitle), resourceCulture);
        public static string MySpace_Welcome => ResourceManager.GetString(nameof(MySpace_Welcome), resourceCulture);
        public static string Page_CreateTitle => ResourceManager.GetString(nameof(Page_CreateTitle), resourceCulture);
        public static string Page_EditTitle => ResourceManager.GetString(nameof(Page_EditTitle), resourceCulture);
        public static string Ph_DeviceId => ResourceManager.GetString(nameof(Ph_DeviceId), resourceCulture);
        public static string Ph_DeviceName => ResourceManager.GetString(nameof(Ph_DeviceName), resourceCulture);
        public static string Ph_NameRequired => ResourceManager.GetString(nameof(Ph_NameRequired), resourceCulture);
        public static string Ph_SurnameRequired => ResourceManager.GetString(nameof(Ph_SurnameRequired), resourceCulture);
        public static string State_AccountConfirmed => ResourceManager.GetString(nameof(State_AccountConfirmed), resourceCulture);
        public static string State_AccountUnconfirmed => ResourceManager.GetString(nameof(State_AccountUnconfirmed), resourceCulture);
        public static string State_Active => ResourceManager.GetString(nameof(State_Active), resourceCulture);
        public static string State_Inactive => ResourceManager.GetString(nameof(State_Inactive), resourceCulture);
        public static string ToastMessage_EmployeeActivated => ResourceManager.GetString(nameof(ToastMessage_EmployeeActivated), resourceCulture);
        public static string ToastMessage_EmployeeDeactivated => ResourceManager.GetString(nameof(ToastMessage_EmployeeDeactivated), resourceCulture);
        public static string ToastMessage_EmployeeDeleted => ResourceManager.GetString(nameof(ToastMessage_EmployeeDeleted), resourceCulture);
        public static string ToastMessage_EmployeeSaved => ResourceManager.GetString(nameof(ToastMessage_EmployeeSaved), resourceCulture);
        public static string ToastMessage_EmployeeUpdated => ResourceManager.GetString(nameof(ToastMessage_EmployeeUpdated), resourceCulture);
        public static string ToastTitle_CreateEmployee => ResourceManager.GetString(nameof(ToastTitle_CreateEmployee), resourceCulture);
        public static string ToastTitle_DeleteEmployee => ResourceManager.GetString(nameof(ToastTitle_DeleteEmployee), resourceCulture);
        public static string ToastTitle_EditEmployee => ResourceManager.GetString(nameof(ToastTitle_EditEmployee), resourceCulture);
        public static string ToastTitle_ToggleEmployee => ResourceManager.GetString(nameof(ToastTitle_ToggleEmployee), resourceCulture);
        public static string Val_CompanyRequired => ResourceManager.GetString(nameof(Val_CompanyRequired), resourceCulture);
        public static string Val_NameRequired => ResourceManager.GetString(nameof(Val_NameRequired), resourceCulture);
        public static string Val_SurnameRequired => ResourceManager.GetString(nameof(Val_SurnameRequired), resourceCulture);
    }
}
