//------------------------------------------------------------------------------
// Auto-generated by _gen_extension_resources.js — Extension UI strings (59
// entries).
//------------------------------------------------------------------------------
namespace Desing.Resources
{
    using System;
    using global::System.Globalization;
    using global::System.Resources;

    /// <summary>TSql_Extension module: localized strings (.resx); UICulture desde LanguageUiHelper.</summary>
    public class Extension
    {
        private static ResourceManager resourceMan;
        private static CultureInfo resourceCulture;

        public static ResourceManager ResourceManager =>
            resourceMan ??
            (resourceMan = new global::Desing.Helpers.DbBackedResourceManager(
                "Desing.Resources.Extension", typeof(Extension).Assembly, "Extension"));

        public static CultureInfo Culture
        {
            get => resourceCulture;
            set => resourceCulture = value;
        }
        public static string Btn_New => ResourceManager.GetString(nameof(Btn_New), resourceCulture);
        public static string Col_DocumentTypes => ResourceManager.GetString(nameof(Col_DocumentTypes), resourceCulture);
        public static string Col_Icon => ResourceManager.GetString(nameof(Col_Icon), resourceCulture);
        public static string Col_MaxFileSize => ResourceManager.GetString(nameof(Col_MaxFileSize), resourceCulture);
        public static string Col_Name => ResourceManager.GetString(nameof(Col_Name), resourceCulture);
        public static string Col_State => ResourceManager.GetString(nameof(Col_State), resourceCulture);
        public static string Common_Home => ResourceManager.GetString(nameof(Common_Home), resourceCulture);
        public static string Common_Settings => ResourceManager.GetString(nameof(Common_Settings), resourceCulture);
        public static string Details_Field_Active => ResourceManager.GetString(nameof(Details_Field_Active), resourceCulture);
        public static string Details_Field_DocumentTypes => ResourceManager.GetString(nameof(Details_Field_DocumentTypes), resourceCulture);
        public static string Details_Field_Icon => ResourceManager.GetString(nameof(Details_Field_Icon), resourceCulture);
        public static string Details_Field_MaxFileSize => ResourceManager.GetString(nameof(Details_Field_MaxFileSize), resourceCulture);
        public static string Details_Field_Name => ResourceManager.GetString(nameof(Details_Field_Name), resourceCulture);
        public static string Details_NoBoolValue => ResourceManager.GetString(nameof(Details_NoBoolValue), resourceCulture);
        public static string Details_NoDocumentTypesAssigned => ResourceManager.GetString(nameof(Details_NoDocumentTypesAssigned), resourceCulture);
        public static string Details_NoValue => ResourceManager.GetString(nameof(Details_NoValue), resourceCulture);
        public static string Details_YesValue => ResourceManager.GetString(nameof(Details_YesValue), resourceCulture);
        public static string Err_CannotDeleteHasDocumentTypes => ResourceManager.GetString(nameof(Err_CannotDeleteHasDocumentTypes), resourceCulture);
        public static string Err_CannotDeleteHasDocuments => ResourceManager.GetString(nameof(Err_CannotDeleteHasDocuments), resourceCulture);
        public static string Err_ExtensionNotFound => ResourceManager.GetString(nameof(Err_ExtensionNotFound), resourceCulture);
        public static string Help_MaxFileSizeBytes => ResourceManager.GetString(nameof(Help_MaxFileSizeBytes), resourceCulture);
        public static string Index_Breadcrumb => ResourceManager.GetString(nameof(Index_Breadcrumb), resourceCulture);
        public static string Index_CreateExtension => ResourceManager.GetString(nameof(Index_CreateExtension), resourceCulture);
        public static string Js_ConfirmDeleteExtension => ResourceManager.GetString(nameof(Js_ConfirmDeleteExtension), resourceCulture);
        public static string Lbl_Active => ResourceManager.GetString(nameof(Lbl_Active), resourceCulture);
        public static string Lbl_ActiveCheckbox => ResourceManager.GetString(nameof(Lbl_ActiveCheckbox), resourceCulture);
        public static string Lbl_DocumentTypesUsage => ResourceManager.GetString(nameof(Lbl_DocumentTypesUsage), resourceCulture);
        public static string Lbl_Icon => ResourceManager.GetString(nameof(Lbl_Icon), resourceCulture);
        public static string Lbl_MaxFileSizeRequired => ResourceManager.GetString(nameof(Lbl_MaxFileSizeRequired), resourceCulture);
        public static string Lbl_NameRequired => ResourceManager.GetString(nameof(Lbl_NameRequired), resourceCulture);
        public static string List_LinkDeleteLockedDocumentTypesTooltip => ResourceManager.GetString(nameof(List_LinkDeleteLockedDocumentTypesTooltip), resourceCulture);
        public static string List_LinkDeleteLockedDocumentsTooltip => ResourceManager.GetString(nameof(List_LinkDeleteLockedDocumentsTooltip), resourceCulture);
        public static string List_LinkDeleteTooltip => ResourceManager.GetString(nameof(List_LinkDeleteTooltip), resourceCulture);
        public static string List_LinkEditTooltip => ResourceManager.GetString(nameof(List_LinkEditTooltip), resourceCulture);
        public static string List_LinkOpenTooltip => ResourceManager.GetString(nameof(List_LinkOpenTooltip), resourceCulture);
        public static string List_NoDocumentTypes => ResourceManager.GetString(nameof(List_NoDocumentTypes), resourceCulture);
        public static string List_NoIcon => ResourceManager.GetString(nameof(List_NoIcon), resourceCulture);
        public static string Page_CreateTitle => ResourceManager.GetString(nameof(Page_CreateTitle), resourceCulture);
        public static string Page_DetailsTitle => ResourceManager.GetString(nameof(Page_DetailsTitle), resourceCulture);
        public static string Page_EditTitle => ResourceManager.GetString(nameof(Page_EditTitle), resourceCulture);
        public static string Ph_MaxFileSize => ResourceManager.GetString(nameof(Ph_MaxFileSize), resourceCulture);
        public static string Ph_Name => ResourceManager.GetString(nameof(Ph_Name), resourceCulture);
        public static string State_Active => ResourceManager.GetString(nameof(State_Active), resourceCulture);
        public static string State_Inactive => ResourceManager.GetString(nameof(State_Inactive), resourceCulture);
        public static string ToastMessage_ExtensionCreated => ResourceManager.GetString(nameof(ToastMessage_ExtensionCreated), resourceCulture);
        public static string ToastMessage_ExtensionDeleted => ResourceManager.GetString(nameof(ToastMessage_ExtensionDeleted), resourceCulture);
        public static string ToastMessage_ExtensionUpdated => ResourceManager.GetString(nameof(ToastMessage_ExtensionUpdated), resourceCulture);
        public static string ToastTitle_CreateExtension => ResourceManager.GetString(nameof(ToastTitle_CreateExtension), resourceCulture);
        public static string ToastTitle_DeleteExtension => ResourceManager.GetString(nameof(ToastTitle_DeleteExtension), resourceCulture);
        public static string ToastTitle_EditExtension => ResourceManager.GetString(nameof(ToastTitle_EditExtension), resourceCulture);
        public static string Val_DuplicateNameCreate => ResourceManager.GetString(nameof(Val_DuplicateNameCreate), resourceCulture);
        public static string Val_DuplicateNameEdit => ResourceManager.GetString(nameof(Val_DuplicateNameEdit), resourceCulture);
        public static string Val_IcoFileMissingExtension => ResourceManager.GetString(nameof(Val_IcoFileMissingExtension), resourceCulture);
        public static string Val_IcoFormatNotAllowed => ResourceManager.GetString(nameof(Val_IcoFormatNotAllowed), resourceCulture);
        public static string Val_IcoPathTooLong => ResourceManager.GetString(nameof(Val_IcoPathTooLong), resourceCulture);
        public static string Val_MaxFileSizeMax => ResourceManager.GetString(nameof(Val_MaxFileSizeMax), resourceCulture);
        public static string Val_MaxFileSizeMin => ResourceManager.GetString(nameof(Val_MaxFileSizeMin), resourceCulture);
        public static string Val_NameRequired => ResourceManager.GetString(nameof(Val_NameRequired), resourceCulture);
        public static string Val_NameTooLong => ResourceManager.GetString(nameof(Val_NameTooLong), resourceCulture);
    }
}
