//------------------------------------------------------------------------------
// Auto-generated by _gen_jobside_resources.js — Jobside UI strings (112
// entries).
//------------------------------------------------------------------------------
namespace Desing.Resources
{
    using System;
    using global::System.Globalization;
    using global::System.Resources;

    /// <summary>TSql_Jobside module: localized strings (.resx); UICulture desde LanguageUiHelper.</summary>
    public class Jobside
    {
        private static ResourceManager resourceMan;
        private static CultureInfo resourceCulture;

        public static ResourceManager ResourceManager =>
            resourceMan ??
            (resourceMan = new global::Desing.Helpers.DbBackedResourceManager(
                "Desing.Resources.Jobside", typeof(Jobside).Assembly, "Jobside"));

        public static CultureInfo Culture
        {
            get => resourceCulture;
            set => resourceCulture = value;
        }
        public static string Btn_New => ResourceManager.GetString(nameof(Btn_New), resourceCulture);
        public static string Col_AddNJobside => ResourceManager.GetString(nameof(Col_AddNJobside), resourceCulture);
        public static string Col_AddNJobsideClient => ResourceManager.GetString(nameof(Col_AddNJobsideClient), resourceCulture);
        public static string Col_Client => ResourceManager.GetString(nameof(Col_Client), resourceCulture);
        public static string Col_LocAddress => ResourceManager.GetString(nameof(Col_LocAddress), resourceCulture);
        public static string Col_Name => ResourceManager.GetString(nameof(Col_Name), resourceCulture);
        public static string Col_State => ResourceManager.GetString(nameof(Col_State), resourceCulture);
        public static string Common_Home => ResourceManager.GetString(nameof(Common_Home), resourceCulture);
        public static string Common_Intranet => ResourceManager.GetString(nameof(Common_Intranet), resourceCulture);
        public static string Details_Field_Active => ResourceManager.GetString(nameof(Details_Field_Active), resourceCulture);
        public static string Details_Field_AddNJobside => ResourceManager.GetString(nameof(Details_Field_AddNJobside), resourceCulture);
        public static string Details_Field_BillAddress => ResourceManager.GetString(nameof(Details_Field_BillAddress), resourceCulture);
        public static string Details_Field_BillSameAsLocLabel => ResourceManager.GetString(nameof(Details_Field_BillSameAsLocLabel), resourceCulture);
        public static string Details_Field_Branch => ResourceManager.GetString(nameof(Details_Field_Branch), resourceCulture);
        public static string Details_Field_Client => ResourceManager.GetString(nameof(Details_Field_Client), resourceCulture);
        public static string Details_Field_ContractRef => ResourceManager.GetString(nameof(Details_Field_ContractRef), resourceCulture);
        public static string Details_Field_JobsideNotes => ResourceManager.GetString(nameof(Details_Field_JobsideNotes), resourceCulture);
        public static string Details_Field_LocAddress => ResourceManager.GetString(nameof(Details_Field_LocAddress), resourceCulture);
        public static string Details_Field_Name => ResourceManager.GetString(nameof(Details_Field_Name), resourceCulture);
        public static string Details_NoBoolValue => ResourceManager.GetString(nameof(Details_NoBoolValue), resourceCulture);
        public static string Details_NoValue => ResourceManager.GetString(nameof(Details_NoValue), resourceCulture);
        public static string Details_Section_BillingDetail => ResourceManager.GetString(nameof(Details_Section_BillingDetail), resourceCulture);
        public static string Details_Section_LocationDetail => ResourceManager.GetString(nameof(Details_Section_LocationDetail), resourceCulture);
        public static string Details_YesValue => ResourceManager.GetString(nameof(Details_YesValue), resourceCulture);
        public static string Docs_Btn_AttachDocument => ResourceManager.GetString(nameof(Docs_Btn_AttachDocument), resourceCulture);
        public static string Docs_Col_Actions => ResourceManager.GetString(nameof(Docs_Col_Actions), resourceCulture);
        public static string Docs_Col_Date => ResourceManager.GetString(nameof(Docs_Col_Date), resourceCulture);
        public static string Docs_Col_Extension => ResourceManager.GetString(nameof(Docs_Col_Extension), resourceCulture);
        public static string Docs_Col_Name => ResourceManager.GetString(nameof(Docs_Col_Name), resourceCulture);
        public static string Docs_Col_Type => ResourceManager.GetString(nameof(Docs_Col_Type), resourceCulture);
        public static string Docs_DownloadTooltip => ResourceManager.GetString(nameof(Docs_DownloadTooltip), resourceCulture);
        public static string Docs_DtTitle => ResourceManager.GetString(nameof(Docs_DtTitle), resourceCulture);
        public static string Docs_NoDocuments => ResourceManager.GetString(nameof(Docs_NoDocuments), resourceCulture);
        public static string Docs_NoFile => ResourceManager.GetString(nameof(Docs_NoFile), resourceCulture);
        public static string Docs_UploadModalTitle => ResourceManager.GetString(nameof(Docs_UploadModalTitle), resourceCulture);
        public static string Docs_Upload_Description => ResourceManager.GetString(nameof(Docs_Upload_Description), resourceCulture);
        public static string Docs_Upload_Failed => ResourceManager.GetString(nameof(Docs_Upload_Failed), resourceCulture);
        public static string Docs_Upload_File => ResourceManager.GetString(nameof(Docs_Upload_File), resourceCulture);
        public static string Docs_Upload_NoDocTypes => ResourceManager.GetString(nameof(Docs_Upload_NoDocTypes), resourceCulture);
        public static string Docs_Upload_Submit => ResourceManager.GetString(nameof(Docs_Upload_Submit), resourceCulture);
        public static string Docs_Upload_Success => ResourceManager.GetString(nameof(Docs_Upload_Success), resourceCulture);
        public static string Docs_Upload_Type => ResourceManager.GetString(nameof(Docs_Upload_Type), resourceCulture);
        public static string Docs_Val_DocTypeInvalid => ResourceManager.GetString(nameof(Docs_Val_DocTypeInvalid), resourceCulture);
        public static string Docs_Val_ExtensionMissing => ResourceManager.GetString(nameof(Docs_Val_ExtensionMissing), resourceCulture);
        public static string Docs_Val_ExtensionNotAllowed => ResourceManager.GetString(nameof(Docs_Val_ExtensionNotAllowed), resourceCulture);
        public static string Docs_Val_FileTooLarge => ResourceManager.GetString(nameof(Docs_Val_FileTooLarge), resourceCulture);
        public static string Docs_Val_NoFile => ResourceManager.GetString(nameof(Docs_Val_NoFile), resourceCulture);
        public static string Docs_Val_SaveFailed => ResourceManager.GetString(nameof(Docs_Val_SaveFailed), resourceCulture);
        public static string Dt_MenuAria => ResourceManager.GetString(nameof(Dt_MenuAria), resourceCulture);
        public static string Dt_Rows_All => ResourceManager.GetString(nameof(Dt_Rows_All), resourceCulture);
        public static string Dt_Rows_N => ResourceManager.GetString(nameof(Dt_Rows_N), resourceCulture);
        public static string Dt_Section_ColumnsVisible => ResourceManager.GetString(nameof(Dt_Section_ColumnsVisible), resourceCulture);
        public static string Dt_Section_Export => ResourceManager.GetString(nameof(Dt_Section_Export), resourceCulture);
        public static string Dt_Section_Records => ResourceManager.GetString(nameof(Dt_Section_Records), resourceCulture);
        public static string Err_CannotDeleteHasDocuments => ResourceManager.GetString(nameof(Err_CannotDeleteHasDocuments), resourceCulture);
        public static string Err_CannotDeleteHasOffers => ResourceManager.GetString(nameof(Err_CannotDeleteHasOffers), resourceCulture);
        public static string Err_JobsideNotFound => ResourceManager.GetString(nameof(Err_JobsideNotFound), resourceCulture);
        public static string Google_NotConfiguredBody => ResourceManager.GetString(nameof(Google_NotConfiguredBody), resourceCulture);
        public static string Google_NotConfiguredStrong => ResourceManager.GetString(nameof(Google_NotConfiguredStrong), resourceCulture);
        public static string Help_AddNJobsidePending => ResourceManager.GetString(nameof(Help_AddNJobsidePending), resourceCulture);
        public static string Help_ContractRefOptional => ResourceManager.GetString(nameof(Help_ContractRefOptional), resourceCulture);
        public static string Index_Breadcrumb => ResourceManager.GetString(nameof(Index_Breadcrumb), resourceCulture);
        public static string Index_CreateJobside => ResourceManager.GetString(nameof(Index_CreateJobside), resourceCulture);
        public static string Js_ConfirmDeleteJobside => ResourceManager.GetString(nameof(Js_ConfirmDeleteJobside), resourceCulture);
        public static string Lbl_Active => ResourceManager.GetString(nameof(Lbl_Active), resourceCulture);
        public static string Lbl_ActiveCheckbox => ResourceManager.GetString(nameof(Lbl_ActiveCheckbox), resourceCulture);
        public static string Lbl_AddNJobside => ResourceManager.GetString(nameof(Lbl_AddNJobside), resourceCulture);
        public static string Lbl_BillAddress => ResourceManager.GetString(nameof(Lbl_BillAddress), resourceCulture);
        public static string Lbl_BillSameAsLoc => ResourceManager.GetString(nameof(Lbl_BillSameAsLoc), resourceCulture);
        public static string Lbl_BillSameAsLocShort => ResourceManager.GetString(nameof(Lbl_BillSameAsLocShort), resourceCulture);
        public static string Lbl_Branch => ResourceManager.GetString(nameof(Lbl_Branch), resourceCulture);
        public static string Lbl_BranchEmpty => ResourceManager.GetString(nameof(Lbl_BranchEmpty), resourceCulture);
        public static string Lbl_Client => ResourceManager.GetString(nameof(Lbl_Client), resourceCulture);
        public static string Lbl_ClientEmpty => ResourceManager.GetString(nameof(Lbl_ClientEmpty), resourceCulture);
        public static string Lbl_ContractRef => ResourceManager.GetString(nameof(Lbl_ContractRef), resourceCulture);
        public static string Lbl_JobsideNotes => ResourceManager.GetString(nameof(Lbl_JobsideNotes), resourceCulture);
        public static string Lbl_LocAddress => ResourceManager.GetString(nameof(Lbl_LocAddress), resourceCulture);
        public static string Lbl_NameRequired => ResourceManager.GetString(nameof(Lbl_NameRequired), resourceCulture);
        public static string List_LinkDeleteLockedDocumentsTooltip => ResourceManager.GetString(nameof(List_LinkDeleteLockedDocumentsTooltip), resourceCulture);
        public static string List_LinkDeleteLockedOffersTooltip => ResourceManager.GetString(nameof(List_LinkDeleteLockedOffersTooltip), resourceCulture);
        public static string List_LinkDeleteTooltip => ResourceManager.GetString(nameof(List_LinkDeleteTooltip), resourceCulture);
        public static string List_LinkEditTooltip => ResourceManager.GetString(nameof(List_LinkEditTooltip), resourceCulture);
        public static string List_LinkOpenTooltip => ResourceManager.GetString(nameof(List_LinkOpenTooltip), resourceCulture);
        public static string List_LinkWorkspaceTooltip => ResourceManager.GetString(nameof(List_LinkWorkspaceTooltip), resourceCulture);
        public static string Page_CreateTitle => ResourceManager.GetString(nameof(Page_CreateTitle), resourceCulture);
        public static string Page_DetailsTitle => ResourceManager.GetString(nameof(Page_DetailsTitle), resourceCulture);
        public static string Page_EditTitle => ResourceManager.GetString(nameof(Page_EditTitle), resourceCulture);
        public static string Ph_ContractRef => ResourceManager.GetString(nameof(Ph_ContractRef), resourceCulture);
        public static string Ph_JobsideNotes => ResourceManager.GetString(nameof(Ph_JobsideNotes), resourceCulture);
        public static string Ph_Name => ResourceManager.GetString(nameof(Ph_Name), resourceCulture);
        public static string State_Active => ResourceManager.GetString(nameof(State_Active), resourceCulture);
        public static string State_Inactive => ResourceManager.GetString(nameof(State_Inactive), resourceCulture);
        public static string Tab_Chat => ResourceManager.GetString(nameof(Tab_Chat), resourceCulture);
        public static string Tab_ComingSoon => ResourceManager.GetString(nameof(Tab_ComingSoon), resourceCulture);
        public static string Tab_Documents => ResourceManager.GetString(nameof(Tab_Documents), resourceCulture);
        public static string Tab_Offers => ResourceManager.GetString(nameof(Tab_Offers), resourceCulture);
        public static string ToastMessage_JobsideCreated => ResourceManager.GetString(nameof(ToastMessage_JobsideCreated), resourceCulture);
        public static string ToastMessage_JobsideDeleted => ResourceManager.GetString(nameof(ToastMessage_JobsideDeleted), resourceCulture);
        public static string ToastMessage_JobsideUpdated => ResourceManager.GetString(nameof(ToastMessage_JobsideUpdated), resourceCulture);
        public static string ToastTitle_CreateJobside => ResourceManager.GetString(nameof(ToastTitle_CreateJobside), resourceCulture);
        public static string ToastTitle_DeleteJobside => ResourceManager.GetString(nameof(ToastTitle_DeleteJobside), resourceCulture);
        public static string ToastTitle_EditJobside => ResourceManager.GetString(nameof(ToastTitle_EditJobside), resourceCulture);
        public static string Val_BranchInvalid => ResourceManager.GetString(nameof(Val_BranchInvalid), resourceCulture);
        public static string Val_BranchRequired => ResourceManager.GetString(nameof(Val_BranchRequired), resourceCulture);
        public static string Val_ClientInvalid => ResourceManager.GetString(nameof(Val_ClientInvalid), resourceCulture);
        public static string Val_DuplicateNameCreate => ResourceManager.GetString(nameof(Val_DuplicateNameCreate), resourceCulture);
        public static string Val_DuplicateNameEdit => ResourceManager.GetString(nameof(Val_DuplicateNameEdit), resourceCulture);
        public static string Val_NameRequired => ResourceManager.GetString(nameof(Val_NameRequired), resourceCulture);
        public static string Workspace_LeftTitle => ResourceManager.GetString(nameof(Workspace_LeftTitle), resourceCulture);
        public static string Workspace_MapTitle => ResourceManager.GetString(nameof(Workspace_MapTitle), resourceCulture);
        public static string Workspace_Tooltip_ExpandPanel => ResourceManager.GetString(nameof(Workspace_Tooltip_ExpandPanel), resourceCulture);
        public static string Workspace_Tooltip_RestorePanel => ResourceManager.GetString(nameof(Workspace_Tooltip_RestorePanel), resourceCulture);
    }
}
