//------------------------------------------------------------------------------
// Auto-generated by _gen_language_resources.js — Language UI strings (75
// entries).
//------------------------------------------------------------------------------
namespace Desing.Resources
{
    using System;
    using global::System.Globalization;
    using global::System.Resources;

    /// <summary>TSql_Language module: localized strings (.resx); UICulture desde LanguageUiHelper.</summary>
    public class Language
    {
        private static ResourceManager resourceMan;
        private static CultureInfo resourceCulture;

        public static ResourceManager ResourceManager =>
            resourceMan ??
            (resourceMan = new global::Desing.Helpers.DbBackedResourceManager(
                "Desing.Resources.Language", typeof(Language).Assembly, "Language"));

        public static CultureInfo Culture
        {
            get => resourceCulture;
            set => resourceCulture = value;
        }
        public static string Btn_New => ResourceManager.GetString(nameof(Btn_New), resourceCulture);
        public static string Col_Code => ResourceManager.GetString(nameof(Col_Code), resourceCulture);
        public static string Col_Country => ResourceManager.GetString(nameof(Col_Country), resourceCulture);
        public static string Col_Default => ResourceManager.GetString(nameof(Col_Default), resourceCulture);
        public static string Col_Flag => ResourceManager.GetString(nameof(Col_Flag), resourceCulture);
        public static string Col_Name => ResourceManager.GetString(nameof(Col_Name), resourceCulture);
        public static string Col_NativeName => ResourceManager.GetString(nameof(Col_NativeName), resourceCulture);
        public static string Col_State => ResourceManager.GetString(nameof(Col_State), resourceCulture);
        public static string Common_Home => ResourceManager.GetString(nameof(Common_Home), resourceCulture);
        public static string Common_Settings => ResourceManager.GetString(nameof(Common_Settings), resourceCulture);
        public static string Country_AriaToggle => ResourceManager.GetString(nameof(Country_AriaToggle), resourceCulture);
        public static string Country_Empty => ResourceManager.GetString(nameof(Country_Empty), resourceCulture);
        public static string Country_LoadError => ResourceManager.GetString(nameof(Country_LoadError), resourceCulture);
        public static string Country_Loading => ResourceManager.GetString(nameof(Country_Loading), resourceCulture);
        public static string Country_TitleToggle => ResourceManager.GetString(nameof(Country_TitleToggle), resourceCulture);
        public static string Details_Field_Code => ResourceManager.GetString(nameof(Details_Field_Code), resourceCulture);
        public static string Details_Field_Country => ResourceManager.GetString(nameof(Details_Field_Country), resourceCulture);
        public static string Details_Field_Default => ResourceManager.GetString(nameof(Details_Field_Default), resourceCulture);
        public static string Details_Field_Flag => ResourceManager.GetString(nameof(Details_Field_Flag), resourceCulture);
        public static string Details_Field_Name => ResourceManager.GetString(nameof(Details_Field_Name), resourceCulture);
        public static string Details_Field_NativeName => ResourceManager.GetString(nameof(Details_Field_NativeName), resourceCulture);
        public static string Details_Field_State => ResourceManager.GetString(nameof(Details_Field_State), resourceCulture);
        public static string Details_NoBoolValue => ResourceManager.GetString(nameof(Details_NoBoolValue), resourceCulture);
        public static string Details_NoValue => ResourceManager.GetString(nameof(Details_NoValue), resourceCulture);
        public static string Details_YesValue => ResourceManager.GetString(nameof(Details_YesValue), resourceCulture);
        public static string Err_CannotDeleteHasCompanies => ResourceManager.GetString(nameof(Err_CannotDeleteHasCompanies), resourceCulture);
        public static string Err_CannotDeleteIsDefault => ResourceManager.GetString(nameof(Err_CannotDeleteIsDefault), resourceCulture);
        public static string Err_LanguageNotFound => ResourceManager.GetString(nameof(Err_LanguageNotFound), resourceCulture);
        public static string Index_Breadcrumb => ResourceManager.GetString(nameof(Index_Breadcrumb), resourceCulture);
        public static string Index_CreateLanguage => ResourceManager.GetString(nameof(Index_CreateLanguage), resourceCulture);
        public static string Index_FallbackNote => ResourceManager.GetString(nameof(Index_FallbackNote), resourceCulture);
        public static string Info_NotDefaultOnCreate => ResourceManager.GetString(nameof(Info_NotDefaultOnCreate), resourceCulture);
        public static string Js_ConfirmDeleteLanguage => ResourceManager.GetString(nameof(Js_ConfirmDeleteLanguage), resourceCulture);
        public static string Lbl_ActiveCheckbox => ResourceManager.GetString(nameof(Lbl_ActiveCheckbox), resourceCulture);
        public static string Lbl_CodeRequired => ResourceManager.GetString(nameof(Lbl_CodeRequired), resourceCulture);
        public static string Lbl_Default => ResourceManager.GetString(nameof(Lbl_Default), resourceCulture);
        public static string Lbl_DefaultCheckbox => ResourceManager.GetString(nameof(Lbl_DefaultCheckbox), resourceCulture);
        public static string Lbl_LinkCountry => ResourceManager.GetString(nameof(Lbl_LinkCountry), resourceCulture);
        public static string Lbl_NameRequired => ResourceManager.GetString(nameof(Lbl_NameRequired), resourceCulture);
        public static string Lbl_NativeName => ResourceManager.GetString(nameof(Lbl_NativeName), resourceCulture);
        public static string Lbl_State => ResourceManager.GetString(nameof(Lbl_State), resourceCulture);
        public static string List_LinkDeleteLockedCompaniesTooltip => ResourceManager.GetString(nameof(List_LinkDeleteLockedCompaniesTooltip), resourceCulture);
        public static string List_LinkDeleteLockedDefaultTooltip => ResourceManager.GetString(nameof(List_LinkDeleteLockedDefaultTooltip), resourceCulture);
        public static string List_LinkDeleteTooltip => ResourceManager.GetString(nameof(List_LinkDeleteTooltip), resourceCulture);
        public static string List_LinkEditTooltip => ResourceManager.GetString(nameof(List_LinkEditTooltip), resourceCulture);
        public static string List_LinkOpenTooltip => ResourceManager.GetString(nameof(List_LinkOpenTooltip), resourceCulture);
        public static string List_NoCountry => ResourceManager.GetString(nameof(List_NoCountry), resourceCulture);
        public static string List_NoFlag => ResourceManager.GetString(nameof(List_NoFlag), resourceCulture);
        public static string List_NoNativeName => ResourceManager.GetString(nameof(List_NoNativeName), resourceCulture);
        public static string Page_CreateTitle => ResourceManager.GetString(nameof(Page_CreateTitle), resourceCulture);
        public static string Page_DetailsTitle => ResourceManager.GetString(nameof(Page_DetailsTitle), resourceCulture);
        public static string Page_EditTitle => ResourceManager.GetString(nameof(Page_EditTitle), resourceCulture);
        public static string Ph_Code => ResourceManager.GetString(nameof(Ph_Code), resourceCulture);
        public static string Ph_CountrySearch => ResourceManager.GetString(nameof(Ph_CountrySearch), resourceCulture);
        public static string Ph_Name => ResourceManager.GetString(nameof(Ph_Name), resourceCulture);
        public static string Ph_NativeName => ResourceManager.GetString(nameof(Ph_NativeName), resourceCulture);
        public static string State_Active => ResourceManager.GetString(nameof(State_Active), resourceCulture);
        public static string State_Default => ResourceManager.GetString(nameof(State_Default), resourceCulture);
        public static string State_DefaultNo => ResourceManager.GetString(nameof(State_DefaultNo), resourceCulture);
        public static string State_DefaultYes => ResourceManager.GetString(nameof(State_DefaultYes), resourceCulture);
        public static string State_Inactive => ResourceManager.GetString(nameof(State_Inactive), resourceCulture);
        public static string ToastMessage_LanguageCreated => ResourceManager.GetString(nameof(ToastMessage_LanguageCreated), resourceCulture);
        public static string ToastMessage_LanguageDeleted => ResourceManager.GetString(nameof(ToastMessage_LanguageDeleted), resourceCulture);
        public static string ToastMessage_LanguageUpdated => ResourceManager.GetString(nameof(ToastMessage_LanguageUpdated), resourceCulture);
        public static string ToastTitle_CreateLanguage => ResourceManager.GetString(nameof(ToastTitle_CreateLanguage), resourceCulture);
        public static string ToastTitle_DeleteLanguage => ResourceManager.GetString(nameof(ToastTitle_DeleteLanguage), resourceCulture);
        public static string ToastTitle_EditLanguage => ResourceManager.GetString(nameof(ToastTitle_EditLanguage), resourceCulture);
        public static string Val_CodeDuplicate => ResourceManager.GetString(nameof(Val_CodeDuplicate), resourceCulture);
        public static string Val_CodeFormat => ResourceManager.GetString(nameof(Val_CodeFormat), resourceCulture);
        public static string Val_CodeRequired => ResourceManager.GetString(nameof(Val_CodeRequired), resourceCulture);
        public static string Val_CodeTooLong => ResourceManager.GetString(nameof(Val_CodeTooLong), resourceCulture);
        public static string Val_DefaultMustExist => ResourceManager.GetString(nameof(Val_DefaultMustExist), resourceCulture);
        public static string Val_NameRequired => ResourceManager.GetString(nameof(Val_NameRequired), resourceCulture);
        public static string Val_NameTooLong => ResourceManager.GetString(nameof(Val_NameTooLong), resourceCulture);
        public static string Val_NativeNameTooLong => ResourceManager.GetString(nameof(Val_NativeNameTooLong), resourceCulture);
    }
}
