//------------------------------------------------------------------------------
// Auto-generated by _gen_offerstate_resources.js — OfferState UI strings (41
// entries).
//------------------------------------------------------------------------------
namespace Desing.Resources
{
    using System;
    using global::System.Globalization;
    using global::System.Resources;

    /// <summary>TSql_OfferState module: localized strings (.resx); UICulture desde LanguageUiHelper.</summary>
    public class OfferState
    {
        private static ResourceManager resourceMan;
        private static CultureInfo resourceCulture;

        public static ResourceManager ResourceManager =>
            resourceMan ??
            (resourceMan = new global::Desing.Helpers.DbBackedResourceManager(
                "Desing.Resources.OfferState", typeof(OfferState).Assembly, "OfferState"));

        public static CultureInfo Culture
        {
            get => resourceCulture;
            set => resourceCulture = value;
        }
        public static string Col_Color => ResourceManager.GetString(nameof(Col_Color), resourceCulture);
        public static string Col_Name => ResourceManager.GetString(nameof(Col_Name), resourceCulture);
        public static string Col_State => ResourceManager.GetString(nameof(Col_State), resourceCulture);
        public static string Common_Home => ResourceManager.GetString(nameof(Common_Home), resourceCulture);
        public static string Common_Settings => ResourceManager.GetString(nameof(Common_Settings), resourceCulture);
        public static string Details_Field_Active => ResourceManager.GetString(nameof(Details_Field_Active), resourceCulture);
        public static string Details_Field_Color => ResourceManager.GetString(nameof(Details_Field_Color), resourceCulture);
        public static string Details_Field_Name => ResourceManager.GetString(nameof(Details_Field_Name), resourceCulture);
        public static string Details_NoColor => ResourceManager.GetString(nameof(Details_NoColor), resourceCulture);
        public static string Err_CannotDeleteHasOffers => ResourceManager.GetString(nameof(Err_CannotDeleteHasOffers), resourceCulture);
        public static string Err_OfferStateNotFound => ResourceManager.GetString(nameof(Err_OfferStateNotFound), resourceCulture);
        public static string Index_Breadcrumb => ResourceManager.GetString(nameof(Index_Breadcrumb), resourceCulture);
        public static string Index_CreateOfferState => ResourceManager.GetString(nameof(Index_CreateOfferState), resourceCulture);
        public static string Js_ConfirmDeleteOfferState => ResourceManager.GetString(nameof(Js_ConfirmDeleteOfferState), resourceCulture);
        public static string Lbl_Active => ResourceManager.GetString(nameof(Lbl_Active), resourceCulture);
        public static string Lbl_ActiveCheckbox => ResourceManager.GetString(nameof(Lbl_ActiveCheckbox), resourceCulture);
        public static string Lbl_Color => ResourceManager.GetString(nameof(Lbl_Color), resourceCulture);
        public static string Lbl_ColorPickerTitle => ResourceManager.GetString(nameof(Lbl_ColorPickerTitle), resourceCulture);
        public static string Lbl_NameRequired => ResourceManager.GetString(nameof(Lbl_NameRequired), resourceCulture);
        public static string List_LinkDeleteLockedOffersTooltip => ResourceManager.GetString(nameof(List_LinkDeleteLockedOffersTooltip), resourceCulture);
        public static string List_LinkDeleteTooltip => ResourceManager.GetString(nameof(List_LinkDeleteTooltip), resourceCulture);
        public static string List_LinkEditTooltip => ResourceManager.GetString(nameof(List_LinkEditTooltip), resourceCulture);
        public static string List_LinkOpenTooltip => ResourceManager.GetString(nameof(List_LinkOpenTooltip), resourceCulture);
        public static string Page_CreateTitle => ResourceManager.GetString(nameof(Page_CreateTitle), resourceCulture);
        public static string Page_DetailsTitle => ResourceManager.GetString(nameof(Page_DetailsTitle), resourceCulture);
        public static string Page_EditTitle => ResourceManager.GetString(nameof(Page_EditTitle), resourceCulture);
        public static string Ph_ColorHex => ResourceManager.GetString(nameof(Ph_ColorHex), resourceCulture);
        public static string Ph_Name => ResourceManager.GetString(nameof(Ph_Name), resourceCulture);
        public static string State_Active => ResourceManager.GetString(nameof(State_Active), resourceCulture);
        public static string State_Inactive => ResourceManager.GetString(nameof(State_Inactive), resourceCulture);
        public static string ToastMessage_OfferStateCreated => ResourceManager.GetString(nameof(ToastMessage_OfferStateCreated), resourceCulture);
        public static string ToastMessage_OfferStateDeleted => ResourceManager.GetString(nameof(ToastMessage_OfferStateDeleted), resourceCulture);
        public static string ToastMessage_OfferStateUpdated => ResourceManager.GetString(nameof(ToastMessage_OfferStateUpdated), resourceCulture);
        public static string ToastTitle_CreateOfferState => ResourceManager.GetString(nameof(ToastTitle_CreateOfferState), resourceCulture);
        public static string ToastTitle_DeleteOfferState => ResourceManager.GetString(nameof(ToastTitle_DeleteOfferState), resourceCulture);
        public static string ToastTitle_EditOfferState => ResourceManager.GetString(nameof(ToastTitle_EditOfferState), resourceCulture);
        public static string Val_ColorInvalidHex => ResourceManager.GetString(nameof(Val_ColorInvalidHex), resourceCulture);
        public static string Val_DuplicateNameCreate => ResourceManager.GetString(nameof(Val_DuplicateNameCreate), resourceCulture);
        public static string Val_DuplicateNameEdit => ResourceManager.GetString(nameof(Val_DuplicateNameEdit), resourceCulture);
        public static string Val_NameRequired => ResourceManager.GetString(nameof(Val_NameRequired), resourceCulture);
        public static string Val_NameTooLong => ResourceManager.GetString(nameof(Val_NameTooLong), resourceCulture);
    }
}
