//------------------------------------------------------------------------------
// Auto-generated by _gen_plantilla_resources.js — Plantilla UI strings (93
// entries).
//------------------------------------------------------------------------------
namespace Desing.Resources
{
    using System;
    using global::System.Globalization;
    using global::System.Resources;

    /// <summary>TSql_Plantilla module: localized strings (.resx); UICulture desde LanguageUiHelper.</summary>
    public class Plantilla
    {
        private static ResourceManager resourceMan;
        private static CultureInfo resourceCulture;

        public static ResourceManager ResourceManager =>
            resourceMan ??
            (resourceMan = new global::Desing.Helpers.DbBackedResourceManager(
                "Desing.Resources.Plantilla", typeof(Plantilla).Assembly, "Plantilla"));

        public static CultureInfo Culture
        {
            get => resourceCulture;
            set => resourceCulture = value;
        }
        public static string Btn_Cancel => ResourceManager.GetString(nameof(Btn_Cancel), resourceCulture);
        public static string Btn_Delete => ResourceManager.GetString(nameof(Btn_Delete), resourceCulture);
        public static string Btn_Edit => ResourceManager.GetString(nameof(Btn_Edit), resourceCulture);
        public static string Btn_Exit => ResourceManager.GetString(nameof(Btn_Exit), resourceCulture);
        public static string Btn_SaveChanges => ResourceManager.GetString(nameof(Btn_SaveChanges), resourceCulture);
        public static string Btn_SavePlantilla => ResourceManager.GetString(nameof(Btn_SavePlantilla), resourceCulture);
        public static string Col_BrandText => ResourceManager.GetString(nameof(Col_BrandText), resourceCulture);
        public static string Col_Color => ResourceManager.GetString(nameof(Col_Color), resourceCulture);
        public static string Col_CreatedDate => ResourceManager.GetString(nameof(Col_CreatedDate), resourceCulture);
        public static string Col_Default => ResourceManager.GetString(nameof(Col_Default), resourceCulture);
        public static string Col_Logo => ResourceManager.GetString(nameof(Col_Logo), resourceCulture);
        public static string Col_Name => ResourceManager.GetString(nameof(Col_Name), resourceCulture);
        public static string Common_Home => ResourceManager.GetString(nameof(Common_Home), resourceCulture);
        public static string Details_Field_AccentColor => ResourceManager.GetString(nameof(Details_Field_AccentColor), resourceCulture);
        public static string Details_Field_BrandText => ResourceManager.GetString(nameof(Details_Field_BrandText), resourceCulture);
        public static string Details_Field_BrandTextColor => ResourceManager.GetString(nameof(Details_Field_BrandTextColor), resourceCulture);
        public static string Details_Field_CreatedDate => ResourceManager.GetString(nameof(Details_Field_CreatedDate), resourceCulture);
        public static string Details_Field_Favicon => ResourceManager.GetString(nameof(Details_Field_Favicon), resourceCulture);
        public static string Details_Field_IsDefault => ResourceManager.GetString(nameof(Details_Field_IsDefault), resourceCulture);
        public static string Details_Field_Logo => ResourceManager.GetString(nameof(Details_Field_Logo), resourceCulture);
        public static string Details_Field_MainColor => ResourceManager.GetString(nameof(Details_Field_MainColor), resourceCulture);
        public static string Details_Field_Name => ResourceManager.GetString(nameof(Details_Field_Name), resourceCulture);
        public static string Details_NoBoolValue => ResourceManager.GetString(nameof(Details_NoBoolValue), resourceCulture);
        public static string Details_NoValue => ResourceManager.GetString(nameof(Details_NoValue), resourceCulture);
        public static string Details_YesValue => ResourceManager.GetString(nameof(Details_YesValue), resourceCulture);
        public static string Dt_MenuAria => ResourceManager.GetString(nameof(Dt_MenuAria), resourceCulture);
        public static string Dt_Rows_All => ResourceManager.GetString(nameof(Dt_Rows_All), resourceCulture);
        public static string Dt_Rows_N => ResourceManager.GetString(nameof(Dt_Rows_N), resourceCulture);
        public static string Dt_Section_ColumnsVisible => ResourceManager.GetString(nameof(Dt_Section_ColumnsVisible), resourceCulture);
        public static string Dt_Section_Export => ResourceManager.GetString(nameof(Dt_Section_Export), resourceCulture);
        public static string Dt_Section_Records => ResourceManager.GetString(nameof(Dt_Section_Records), resourceCulture);
        public static string Err_CannotDeleteDefault => ResourceManager.GetString(nameof(Err_CannotDeleteDefault), resourceCulture);
        public static string Err_FaviconFormatNotAllowed => ResourceManager.GetString(nameof(Err_FaviconFormatNotAllowed), resourceCulture);
        public static string Err_FaviconSaveFailed => ResourceManager.GetString(nameof(Err_FaviconSaveFailed), resourceCulture);
        public static string Err_FaviconTooLarge => ResourceManager.GetString(nameof(Err_FaviconTooLarge), resourceCulture);
        public static string Err_LogoFormatNotAllowed => ResourceManager.GetString(nameof(Err_LogoFormatNotAllowed), resourceCulture);
        public static string Err_LogoSaveFailed => ResourceManager.GetString(nameof(Err_LogoSaveFailed), resourceCulture);
        public static string Err_LogoTooLarge => ResourceManager.GetString(nameof(Err_LogoTooLarge), resourceCulture);
        public static string Err_PlantillaNotFound => ResourceManager.GetString(nameof(Err_PlantillaNotFound), resourceCulture);
        public static string Help_BrandText => ResourceManager.GetString(nameof(Help_BrandText), resourceCulture);
        public static string Help_BrandTextColor => ResourceManager.GetString(nameof(Help_BrandTextColor), resourceCulture);
        public static string Help_FaviconSize => ResourceManager.GetString(nameof(Help_FaviconSize), resourceCulture);
        public static string Help_LogoFormats => ResourceManager.GetString(nameof(Help_LogoFormats), resourceCulture);
        public static string Help_OnlyOneDefault => ResourceManager.GetString(nameof(Help_OnlyOneDefault), resourceCulture);
        public static string Index_Breadcrumb => ResourceManager.GetString(nameof(Index_Breadcrumb), resourceCulture);
        public static string Index_CreatePlantilla => ResourceManager.GetString(nameof(Index_CreatePlantilla), resourceCulture);
        public static string Js_ConfirmDeletePlantilla => ResourceManager.GetString(nameof(Js_ConfirmDeletePlantilla), resourceCulture);
        public static string Js_FileTooLargeFavicon => ResourceManager.GetString(nameof(Js_FileTooLargeFavicon), resourceCulture);
        public static string Js_FileTooLargeLogo => ResourceManager.GetString(nameof(Js_FileTooLargeLogo), resourceCulture);
        public static string Lbl_BrandAccentColor => ResourceManager.GetString(nameof(Lbl_BrandAccentColor), resourceCulture);
        public static string Lbl_BrandAccentColorTitle => ResourceManager.GetString(nameof(Lbl_BrandAccentColorTitle), resourceCulture);
        public static string Lbl_BrandTextColor => ResourceManager.GetString(nameof(Lbl_BrandTextColor), resourceCulture);
        public static string Lbl_BrandTextColorTitle => ResourceManager.GetString(nameof(Lbl_BrandTextColorTitle), resourceCulture);
        public static string Lbl_BrandTextRequired => ResourceManager.GetString(nameof(Lbl_BrandTextRequired), resourceCulture);
        public static string Lbl_Favicon => ResourceManager.GetString(nameof(Lbl_Favicon), resourceCulture);
        public static string Lbl_IsDefault => ResourceManager.GetString(nameof(Lbl_IsDefault), resourceCulture);
        public static string Lbl_Logo => ResourceManager.GetString(nameof(Lbl_Logo), resourceCulture);
        public static string Lbl_MainColor => ResourceManager.GetString(nameof(Lbl_MainColor), resourceCulture);
        public static string Lbl_NameRequired => ResourceManager.GetString(nameof(Lbl_NameRequired), resourceCulture);
        public static string List_DefaultLockedTooltip => ResourceManager.GetString(nameof(List_DefaultLockedTooltip), resourceCulture);
        public static string List_LinkDeleteTooltip => ResourceManager.GetString(nameof(List_LinkDeleteTooltip), resourceCulture);
        public static string List_LinkEditTooltip => ResourceManager.GetString(nameof(List_LinkEditTooltip), resourceCulture);
        public static string List_LinkOpenTooltip => ResourceManager.GetString(nameof(List_LinkOpenTooltip), resourceCulture);
        public static string Msg_PlantillaDeleted => ResourceManager.GetString(nameof(Msg_PlantillaDeleted), resourceCulture);
        public static string Page_CreateTitle => ResourceManager.GetString(nameof(Page_CreateTitle), resourceCulture);
        public static string Page_EditTitle => ResourceManager.GetString(nameof(Page_EditTitle), resourceCulture);
        public static string Ph_BrandText => ResourceManager.GetString(nameof(Ph_BrandText), resourceCulture);
        public static string Ph_BrandTextColor => ResourceManager.GetString(nameof(Ph_BrandTextColor), resourceCulture);
        public static string Ph_FaviconPath => ResourceManager.GetString(nameof(Ph_FaviconPath), resourceCulture);
        public static string Ph_LogoPath => ResourceManager.GetString(nameof(Ph_LogoPath), resourceCulture);
        public static string Ph_Name => ResourceManager.GetString(nameof(Ph_Name), resourceCulture);
        public static string Preview_ColorLabel => ResourceManager.GetString(nameof(Preview_ColorLabel), resourceCulture);
        public static string Preview_Title => ResourceManager.GetString(nameof(Preview_Title), resourceCulture);
        public static string State_Default => ResourceManager.GetString(nameof(State_Default), resourceCulture);
        public static string State_NotDefault => ResourceManager.GetString(nameof(State_NotDefault), resourceCulture);
        public static string ToastMessage_DbBrandColumnsMissing => ResourceManager.GetString(nameof(ToastMessage_DbBrandColumnsMissing), resourceCulture);
        public static string ToastMessage_PlantillaCreated => ResourceManager.GetString(nameof(ToastMessage_PlantillaCreated), resourceCulture);
        public static string ToastMessage_PlantillaDeleted => ResourceManager.GetString(nameof(ToastMessage_PlantillaDeleted), resourceCulture);
        public static string ToastMessage_PlantillaUpdated => ResourceManager.GetString(nameof(ToastMessage_PlantillaUpdated), resourceCulture);
        public static string ToastTitle_CreatePlantilla => ResourceManager.GetString(nameof(ToastTitle_CreatePlantilla), resourceCulture);
        public static string ToastTitle_DbError => ResourceManager.GetString(nameof(ToastTitle_DbError), resourceCulture);
        public static string ToastTitle_DeletePlantilla => ResourceManager.GetString(nameof(ToastTitle_DeletePlantilla), resourceCulture);
        public static string ToastTitle_EditPlantilla => ResourceManager.GetString(nameof(ToastTitle_EditPlantilla), resourceCulture);
        public static string Val_AccentColorHexFormat => ResourceManager.GetString(nameof(Val_AccentColorHexFormat), resourceCulture);
        public static string Val_AccentColorRequired => ResourceManager.GetString(nameof(Val_AccentColorRequired), resourceCulture);
        public static string Val_BrandTextColorHexFormat => ResourceManager.GetString(nameof(Val_BrandTextColorHexFormat), resourceCulture);
        public static string Val_BrandTextRequired => ResourceManager.GetString(nameof(Val_BrandTextRequired), resourceCulture);
        public static string Val_DuplicateNameCreate => ResourceManager.GetString(nameof(Val_DuplicateNameCreate), resourceCulture);
        public static string Val_DuplicateNameEdit => ResourceManager.GetString(nameof(Val_DuplicateNameEdit), resourceCulture);
        public static string Val_LogoPathRequired => ResourceManager.GetString(nameof(Val_LogoPathRequired), resourceCulture);
        public static string Val_MainColorHexFormat => ResourceManager.GetString(nameof(Val_MainColorHexFormat), resourceCulture);
        public static string Val_MainColorRequired => ResourceManager.GetString(nameof(Val_MainColorRequired), resourceCulture);
        public static string Val_NameRequired => ResourceManager.GetString(nameof(Val_NameRequired), resourceCulture);
    }
}
