//------------------------------------------------------------------------------
// Auto-generated by _gen_xrdevice_resources.js — XrDevice UI strings.
//------------------------------------------------------------------------------
namespace Desing.Resources
{
    using System;
    using global::System.Globalization;
    using global::System.Resources;

    /// <summary>TSql_XrDevice module: localized strings (.resx); UICulture desde LanguageUiHelper.</summary>
    public class XrDevice
    {
        private static ResourceManager resourceMan;
        private static CultureInfo resourceCulture;

        public static ResourceManager ResourceManager =>
            resourceMan ??
            (resourceMan = new global::Desing.Helpers.DbBackedResourceManager(
                "Desing.Resources.XrDevice", typeof(XrDevice).Assembly, "XrDevice"));

        public static CultureInfo Culture
        {
            get => resourceCulture;
            set => resourceCulture = value;
        }

        public static string Col_Name => ResourceManager.GetString(nameof(Col_Name), resourceCulture);
        public static string Col_Paired => ResourceManager.GetString(nameof(Col_Paired), resourceCulture);
        public static string Col_Pairing => ResourceManager.GetString(nameof(Col_Pairing), resourceCulture);
        public static string Col_State => ResourceManager.GetString(nameof(Col_State), resourceCulture);
        public static string Col_Type => ResourceManager.GetString(nameof(Col_Type), resourceCulture);
        public static string Common_Home => ResourceManager.GetString(nameof(Common_Home), resourceCulture);
        public static string Common_Settings => ResourceManager.GetString(nameof(Common_Settings), resourceCulture);
        public static string Details_Field_Active => ResourceManager.GetString(nameof(Details_Field_Active), resourceCulture);
        public static string Details_Field_LastSeen => ResourceManager.GetString(nameof(Details_Field_LastSeen), resourceCulture);
        public static string Details_Field_Name => ResourceManager.GetString(nameof(Details_Field_Name), resourceCulture);
        public static string Details_Field_Notes => ResourceManager.GetString(nameof(Details_Field_Notes), resourceCulture);
        public static string Details_Field_Paired => ResourceManager.GetString(nameof(Details_Field_Paired), resourceCulture);
        public static string Details_Field_Pairing => ResourceManager.GetString(nameof(Details_Field_Pairing), resourceCulture);
        public static string Details_Field_Type => ResourceManager.GetString(nameof(Details_Field_Type), resourceCulture);
        public static string Details_NeverSeen => ResourceManager.GetString(nameof(Details_NeverSeen), resourceCulture);
        public static string Details_NoNotes => ResourceManager.GetString(nameof(Details_NoNotes), resourceCulture);
        public static string Err_NotFound => ResourceManager.GetString(nameof(Err_NotFound), resourceCulture);
        public static string Err_TablesMissing => ResourceManager.GetString(nameof(Err_TablesMissing), resourceCulture);
        public static string Index_Breadcrumb => ResourceManager.GetString(nameof(Index_Breadcrumb), resourceCulture);
        public static string Index_Create => ResourceManager.GetString(nameof(Index_Create), resourceCulture);
        public static string Js_ConfirmDelete => ResourceManager.GetString(nameof(Js_ConfirmDelete), resourceCulture);
        public static string Lbl_Active => ResourceManager.GetString(nameof(Lbl_Active), resourceCulture);
        public static string Lbl_ActiveCheckbox => ResourceManager.GetString(nameof(Lbl_ActiveCheckbox), resourceCulture);
        public static string Lbl_NameRequired => ResourceManager.GetString(nameof(Lbl_NameRequired), resourceCulture);
        public static string Lbl_Notes => ResourceManager.GetString(nameof(Lbl_Notes), resourceCulture);
        public static string Lbl_Pairing => ResourceManager.GetString(nameof(Lbl_Pairing), resourceCulture);
        public static string Lbl_Type => ResourceManager.GetString(nameof(Lbl_Type), resourceCulture);
        public static string List_LinkDeleteTooltip => ResourceManager.GetString(nameof(List_LinkDeleteTooltip), resourceCulture);
        public static string List_LinkEditTooltip => ResourceManager.GetString(nameof(List_LinkEditTooltip), resourceCulture);
        public static string List_LinkOpenTooltip => ResourceManager.GetString(nameof(List_LinkOpenTooltip), resourceCulture);
        public static string Page_CreateTitle => ResourceManager.GetString(nameof(Page_CreateTitle), resourceCulture);
        public static string Page_DetailsTitle => ResourceManager.GetString(nameof(Page_DetailsTitle), resourceCulture);
        public static string Page_EditTitle => ResourceManager.GetString(nameof(Page_EditTitle), resourceCulture);
        public static string Ph_Name => ResourceManager.GetString(nameof(Ph_Name), resourceCulture);
        public static string Ph_Notes => ResourceManager.GetString(nameof(Ph_Notes), resourceCulture);
        public static string Ph_Pairing => ResourceManager.GetString(nameof(Ph_Pairing), resourceCulture);
        public static string State_Active => ResourceManager.GetString(nameof(State_Active), resourceCulture);
        public static string State_Inactive => ResourceManager.GetString(nameof(State_Inactive), resourceCulture);
        public static string State_Paired => ResourceManager.GetString(nameof(State_Paired), resourceCulture);
        public static string State_Unpaired => ResourceManager.GetString(nameof(State_Unpaired), resourceCulture);
        public static string ToastMessage_Created => ResourceManager.GetString(nameof(ToastMessage_Created), resourceCulture);
        public static string ToastMessage_Deleted => ResourceManager.GetString(nameof(ToastMessage_Deleted), resourceCulture);
        public static string ToastMessage_Updated => ResourceManager.GetString(nameof(ToastMessage_Updated), resourceCulture);
        public static string ToastTitle_Create => ResourceManager.GetString(nameof(ToastTitle_Create), resourceCulture);
        public static string ToastTitle_Delete => ResourceManager.GetString(nameof(ToastTitle_Delete), resourceCulture);
        public static string ToastTitle_Edit => ResourceManager.GetString(nameof(ToastTitle_Edit), resourceCulture);
        public static string Type_Quest => ResourceManager.GetString(nameof(Type_Quest), resourceCulture);
        public static string Type_Tablet => ResourceManager.GetString(nameof(Type_Tablet), resourceCulture);
        public static string Val_DuplicateNameCreate => ResourceManager.GetString(nameof(Val_DuplicateNameCreate), resourceCulture);
        public static string Val_DuplicateNameEdit => ResourceManager.GetString(nameof(Val_DuplicateNameEdit), resourceCulture);
        public static string Val_DuplicatePairing => ResourceManager.GetString(nameof(Val_DuplicatePairing), resourceCulture);
        public static string Val_NameRequired => ResourceManager.GetString(nameof(Val_NameRequired), resourceCulture);
        public static string Val_NameTooLong => ResourceManager.GetString(nameof(Val_NameTooLong), resourceCulture);
        public static string Val_PairingRequired => ResourceManager.GetString(nameof(Val_PairingRequired), resourceCulture);
        public static string Val_PairingTooLong => ResourceManager.GetString(nameof(Val_PairingTooLong), resourceCulture);
    }
}
